### ISSUE TITLE
Memory leaks in examples

### ISSUE THREAD

**Issue by davidbyttow** [davidbyttow/govips#1]
Most likely this is just related to not unref'ing all objects as they're used.

**Comment by jcupitt** [comment]
You probably know, but there's `vips_object_print_all()`. It dumps a list of all current active objects, with a ref count for each one. You can insert a call before and after some action in your binding, then diff the output and verify that the counts have changed as you expect.

**Comment by davidbyttow** [comment]
Thanks @jcupitt!

**Comment by kgdev** [comment]
Any updates?

**Comment by davidbyttow** [comment]
Fixed!
