### ISSUE TITLE
How to add this lib ?

### ISSUE THREAD

**Issue by mohit810** [davidbyttow/govips#100]
I know Its simple but I am new at Go and facing issue.

on installation using 

 ```
go get -u github.com/davidbyttow/govips/pkg/vips

```
I am getting

```
# pkg-config --cflags  -- vips vips vips vips vips vips vips vips vips
pkg-config: exec: "pkg-config": executable file not found in %PATH%

```

**Comment by tonimelisma** [comment]
You need to install pkg-config. If you're on Mac, try homebrew (`homebrew install pkg-config`) and if you're on Ubuntu, `sudo apt install pkg-config`

You probably also need the relevant libraries and their header files (`homebrew install vips`or `sudo apt install libvips-dev`)

**Comment by mohit810** [comment]
> You need to install pkg-config. If you're on Mac, try homebrew (`homebrew install pkg-config`) and if you're on Ubuntu, `sudo apt install pkg-config`
> 
> You probably also need the relevant libraries and their header files (`homebrew install vips`or `sudo apt install libvips-dev`)

 i have ubuntu on vm, will try the steps u mentioned on it but is there any way of testing it on windows?

**Comment by tonimelisma** [comment]
Yeah, both libvips as well as govips should work on Windows. Try and get libvips first installed (from their github) and work from there. Apologies, but not actively using Windows right now so can't provide more guidance.

**Comment by mohit810** [comment]
> Yeah, both libvips as well as govips should work on Windows. Try and get libvips first installed (from their github) and work from there. Apologies, but not actively using Windows right now so can't provide more guidance.

It's really great that u could point me in the right direction. I am glad for that and one last thing, if u don't mind I found ur recommendation of the other fork. For this https://github.com/wix-playground/govips fork do i have to pre-install something or just "go get - u.." will be enough?

**Comment by tonimelisma** [comment]
The exact same prerequisites, both pkg-config as well as libvips-dev.

**Comment by tonimelisma** [comment]
Hey @mohit810 I've now fixed the latest govips version here and integrated all the improvements from the wix-playground fork. The API has changed quite a bit. The README should have clear instructions on both how to install dependencies as well as how to get govips working. If there's any issues you run into, let me know.

If you figure out how to get govips working on Windows, please let me know what's required!
