### ISSUE TITLE
Is there any plan to add avif support.

### ISSUE THREAD

**Issue by amittal-quot** [davidbyttow/govips#101]
Looks like libvips support avif files, is there any plan to support avif in this?

**Comment by tonimelisma** [comment]
Hey @amittal-quot might be. Do you have time and energy to try to do a PR yourself or is this purely a feature request? Thanks for using govips!

**Comment by tonimelisma** [comment]
Hey @amittal-quot govips 2.0 has support for AVIF files, nothing special required. If you have any issues, let me know!
