### ISSUE TITLE
Fails to compile when upgrading go

### ISSUE THREAD

**Issue by aliak00** [davidbyttow/govips#105]
I recently upgraded go from 1.13 to 1.15. And for some reason the the warnings that's mentioned in #99 is now an error. Tried the following:

* Settings `CGO_CFLAGS` to `-Wno-implicit-function-declaration`
* Adding `// #cgo CFLAGS: -Wno-implicit-function-declaration` to before the:
  ```
  // #include <vips/vips.h>
  import "C"
  ```
* Tried `go build -gcflags "-Wno-implicit-function-declaration"`

I'm a bit stumped here. Anyone having this experience? 

I updated go via brew. I tried to downgrade to 1.14.9 and it didn't help. Also just tried going back to 1.13, didn't help.

**Comment by tonimelisma** [comment]
In case your Dockerfile in the issue #99 is still relevant, you're building against VIPS 8.10 which no longer has the function in question, it's been dropped from the API. Just clean up all mentions related to autorot_get_angle and related functions from bridge.go, bridge.c and bridge.h

**Comment by tonimelisma** [comment]
Hey @aliak00 the bug has now been fixed in the latest govips, if you'll update to it. Can you check that it works for you? N.B. the API has changed quite a bit, check the README for a fresh example.

**Comment by aliak00** [comment]
Sweet! Thanks for the heads up! Will update when we get around to the change! (we ended up locking it to an older version before).
