### ISSUE TITLE
could not determine kind of name for C.free

### ISSUE THREAD

**Issue by phanirithvij** [davidbyttow/govips#112]
On windows when I'm installing via the following command as specified in the readme (after downloading the libvips and setting it all up)

```
$ go get -u -v github.com/davidbyttow/govips/v2/vips
```

```
go: found github.com/davidbyttow/govips/v2/vips in github.com/davidbyttow/govips/v2 v2.0.1
go: golang.org/x/text upgrade => v0.3.4
go: golang.org/x/net upgrade => v0.0.0-20201027133719-8eef5233e2a1
github.com/davidbyttow/govips/v2/vips
# github.com/davidbyttow/govips/v2/vips
C:\Users\Rithvij\go\pkg\mod\github.com\davidbyttow\govips\v2@v2.0.1\vips\lang.go:12:2: could not determine kind of name for C.free
```

I was able to fix it by adding `// #include <stdlib.h>` in line 3 of lang.go and building again `go build -v github.com/davidbyttow/govips/v2/vips`

Can it be fixed? Seems like a simple fix.

**Comment by tonimelisma** [comment]
Hey @phanirithvij apologies for not noticing this sooner. Does the suggest PR fix this for you?

On a related note, if I were to add Windows as one of the CI/CD and test automation sources, how did you build the latest libvips there?

**Comment by phanirithvij** [comment]
I just downloaded from libvips releases and added it to path and used cgo flags to point to the include directory and library paths
But if building libvips is required the wiki of libvips repo has https://github.com/libvips/libvips/wiki/Build-for-Windows

**Comment by tonimelisma** [comment]
Hey @phanirithvij thanks for the info, great that it works for you. I tried looking at the tooling on Windows and I consider it a bit too tricky to include in our regularly supported and tested environments. If possible, I would recommend using WSL under Windows to develop and build govips, if that's an option for you.
