### ISSUE TITLE
Support animated images

### ISSUE THREAD

**Issue by Elad-Laufer** [davidbyttow/govips#117]
Test and if _needed_ implement the following for animated images:

Note: libvips loads the pages into a roll

**IO**

- Load all image pages
- When saving to formats that do not support animation (such as JPG) - save the first page and not the roll

**Operations**

1. Resize - might need to adjust the page hight property
2. Rotate - might need to splice a new roll
3. Flip - make sure that the page order does change
4. ExtractArea - might need to splice a new roll
5. Label - label a selected page (all pages as an option)?
6. Extend - might need to splice a new roll

**Discussion**

Composite:

compose on each page - I think this should be the default behavior, as we use compose primarily for watermarking
compose 2 animated images? - should we define the behavior?

**Comment by tonimelisma** [comment]
Looks great to me. Likely would be most logical if Label() and Composite() both function in a similar fashion. I think the primary use case of both is watermarking so probably makes sense if both default to all pages.

**Comment by Elad-Laufer** [comment]
https://github.com/davidbyttow/govips/pull/246

**Comment by AttilaTheFun** [comment]
@Elad-Laufer this seems to be working now! Do you want to close it? Or is there still work to be done.

**Comment by Elad-Laufer** [comment]
> @Elad-Laufer this seems to be working now! Do you want to close it? Or is there still work to be done.

Not all the features are supported yet, currently only resize is covered 100% for multipages images.

See https://github.com/davidbyttow/govips/issues/248 and https://github.com/davidbyttow/govips/issues/249 for example.

**Comment by davidbyttow** [comment]
We should perhaps re-word this or close the issue and just use other issues for the additional features. We technically now support animated images.

**Comment by davidbyttow** [comment]
Closing this for now
