### ISSUE TITLE
WebP ICC profiles are not embedded

### ISSUE THREAD

**Issue by Elad-Laufer** [davidbyttow/govips#122]
@alon-ne is working on a fix #120

**Comment by tonimelisma** [comment]
Thanks, looking forward to the PR. I assume you will drop the sharpen commit as well as anything else which is not compatible with vanilla libvips.

I'll try and rework the golden test images back as well, so go ahead and recommit the full unit testing logic for those. I can then further develop that unit testing logic to compare to OS release specific images (e.g. test-macos-catalina.jpg or test-ubuntu-bionic.jpg test-ubuntu-groovy.jpg).

**Comment by Elad-Laufer** [comment]
The sharpen is not included in this PR, the messy commit log is the result of all the merges between forks.

I hope that after this PR the 2 forks won't diverge as much and maintaining both forks won't prove so troublesome...

**Comment by tonimelisma** [comment]
Agreed. After working back the golden image tests I would expect there will not be any major divergencies between the forks except for wix-specific stuff you will have on your side.

I will also hold on to backwards compatibility.

And please, if you see anything here in the issues which conflicts your development roadmap, please don't hesitate to comment!

**Comment by Elad-Laufer** [comment]
fixed
