### ISSUE TITLE
NewImageFromBuffer Not Understand Image Format

### ISSUE THREAD

**Issue by dadaocongsanvietnam** [davidbyttow/govips#124]
Hi there,

```
import "bytes"
import "image"
import "image/color"
import "image/png"
import "image/draw"

im := image.NewRGBA(image.Rect(0, 0, 100, 100))
draw.Draw(im, im.Bounds(), image.NewUniform(color.NRGBA{255, 0, 0, 255}), image.ZP, draw.Src)
var buff bytes.Buffer
err := png.Encode(&buff, im)

vipsImage, err := vips.NewImageFromBuffer(buff.Bytes())
```

[govips.info] failed to understand image format size=26149

Any suggestions how to solve this?

**Comment by tonimelisma** [comment]
What if you save the contents of buff into a .png image on your hard drive. Is it a valid png file, can you open it?

**Comment by dadaocongsanvietnam** [comment]
I want to create many images in memory, resize and composite them before save to disk

**Comment by tonimelisma** [comment]
Sure. I'm just wondering, to debug your code, if it made sense to take it a step at a time. Have you checked that your code is capable of producing valid .png files which you can open?

**Comment by dadaocongsanvietnam** [comment]
```
import "bufio"
import "os"
import "bytes"
import "image"
import "image/color"
import "image/png"
import "image/draw"

im := image.NewRGBA(image.Rect(0, 0, 100, 100))
draw.Draw(im, im.Bounds(), image.NewUniform(color.NRGBA{255, 0, 0, 255}), image.ZP, draw.Src)
var buff bytes.Buffer
err := png.Encode(&buff, im)

fo, err := os.Create("img.png")
defer fo.Close()
fw := bufio.NewWriter(fo)
fw.Write(buff.Bytes())
fw.Flush()

vipsImage, err := vips.NewImageFromBuffer(buff.Bytes())
```

Yes, It is valid png file

**Comment by Elad-Laufer** [comment]
The error '[govips.info] failed to understand image format size=26149' stats that the data size is 26149 bytes, while the file is 292 bytes. 

Maybe the buffer was changed before buff.Bytes() was called?

**Comment by dadaocongsanvietnam** [comment]
imageType is 7, but IsTypeSupported is false

**Comment by dadaocongsanvietnam** [comment]
Change govips.go file:
initTypes {
...
if supportedImageTypes[k] {
   govipsLog("govips", LogLevelInfo, fmt.Sprintf("registered image type loader type=%s", v))
}
...
}

**Comment by tonimelisma** [comment]
Thank you @dadaocongsanvietnam for the bug report. I've fixed this in the latest.
