### ISSUE TITLE
Error with resize example: Memory leaks: resize...

### ISSUE THREAD

**Issue by montanaflynn** [davidbyttow/govips#13]
Running https://github.com/davidbyttow/govips/blob/master/examples/resize/resize.go prints an error and generates no output file.

```
$ go run test.go in.gif out.gif

=======================================
Memory leaks: resize...
=======================================
```

Compared to cli which worked:

```
$ vips in.gif out.gif 0.2
```

**Comment by davidbyttow** [comment]
Will look!

**Comment by davidbyttow** [comment]
oh, you need to set the flags.   go run test.go --in=in.gif --out=out.gif

**Comment by montanaflynn** [comment]
Wow not sure how I missed that, now I get the output file but it still prints the memory leaks output.

**Comment by davidbyttow** [comment]
fixed!
