### ISSUE TITLE
Mapim ?

### ISSUE THREAD

**Issue by axkirillov** [davidbyttow/govips#131]
I want to perform an analog to imagemagick's distort. According to this article http://libvips.blogspot.com/2015/11/fancy-transforms.html I can do it using mapim. However I haven't found any mapim bindings here.

**Comment by tonimelisma** [comment]
Thanks for the comment @charlieheart. Indeed we haven't created a binding mapim() binding in govips yet. Would you be interested in creating a PR or is this simply a feature request?

**Comment by charlieheart** [comment]
@charlieheart  Sure, I could try to make a PR. I cloned the library and all tests are failing for me. Do you know what might be the problem?

**Comment by tonimelisma** [comment]
Hmm. Could you be more specific, what steps you took and what sort of errors did you get?

**Comment by charlieheart** [comment]
When I clone the repo I ran go test in the root directory and 32 out of 53 tests are failing (so not all of them, as I said earlier). They fail normally, as in they indicate that actual and expected are different. But I didn't perform any changes on the repository. Could this be a setup issue? I'm running on mac.My version of VIPS is 8.10.2_4

**Comment by tonimelisma** [comment]
Hey @charlieheart thanks for the enthusiasm. Yes, it's likely an issue with your personal setup. All tests are working well for me both on my personal mac as well as Github CI/CD macs (both catalina and big sur). I'm not sure how familiar you are with the Go language generally? As a first step I would suggest doing some general tutorials if you haven't, especially related to cgo, and then drilling into the govips code and debugging why the tests are failing. Once you have a better understanding of the internal workings of govips and your development environment is all good, you might try and explain a high-level design of how you'd approach doing the PR and we can discuss.

Does that make sense?

**Comment by charlieheart** [comment]
@tonimelisma thank you for your reply. Yes I am somewhat familiar with go, not so much with cgo.
Here is how the perspective distort can be done in ruby
`#!/usr/bin/ruby

require 'vips'

image = Vips::Image.new_from_file ARGV[0]

# perspective distortion: each pixel (x', y') in the output image is
# interpolated from pixel (x, y) in the input using:
#
#   x' = (A x + B y + C) / (G x + H y + 1)
#   y' = (D x + E y + F) / (G x + H y + 1)
#
# where the constants A .. H are from the transform matrix T
#
# T = [A, B, .. H]

T = [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0003, 0.0001]

# make an index image where pixels have the value of their (x, y) coordinates
i = Vips::Image.xyz image.width, image.height

x = (i[0] * T[0] + i[1] * T[1] + T[2]) / (i[0] * T[6] + i[1] * T[7] + 1)
y = (i[0] * T[2] + i[1] * T[4] + T[5]) / (i[0] * T[6] + i[1] * T[7] + 1)

# join up x and y as a map image
m = x.bandjoin y

# and use it to transform our original image
image = image.mapim m 

image.write_to_file ARGV[1]`

we already have bandjoin, which is good
I tried to implement xyz, and it passes the smoke test. But what I fail to understand is how can I do this

**Comment by charlieheart** [comment]
I think I know. In ruby-vips documentation it says

#[](index) ⇒ Image
Fetch bands using a number or a range.

So this is just getting a band

**Comment by axkirillov** [comment]
Can I add number to image using vipsAdd?

**Comment by tonimelisma** [comment]
Thanks a lot for the PRs @axkirillov! Great job!!
