### ISSUE TITLE
[Feature Request] Add support of generate diffed image.

### ISSUE THREAD

**Issue by zzjin** [davidbyttow/govips#133]
In my case, I want to combine multiple images together and then generate min common diffs pixels to another image.
Already working on one pr but wondering features like these match this repo or not.
IMO, these features sounds not common for image processing like bimg but useful for repos at lower go-binding for libvips.
libvips discussion: 
https://github.com/libvips/libvips/issues/1919
https://github.com/libvips/libvips/issues/1923

**Comment by tonimelisma** [comment]
Hey zzjin. It doesn't look like a common use case. I'm wary of adding too much rarely used functionality into govips as it adds to the complexity of the library as well as to maintenance costs. Govips doesn't have many maintainers and we're always short on time. Perhaps it would be best if the functionality you're looking for would be done in a separate library on top of govips?

Thanks for the all the enthusiasm and help.

**Comment by zzjin** [comment]
I know, I agree.
Thanks for such great repo again.

**Comment by tonimelisma** [comment]
Thanks for all the feedback and PRs @zzjin!
