### ISSUE TITLE
govips aggressive memory usage

### ISSUE THREAD

**Issue by tonimelisma** [davidbyttow/govips#136]
Running [fastgallery](https://github.com/tonimelisma/fastgallery) which uses the latest govips w/ libvips 8.10.2 on either Ubuntu 20.10 or macOS 11.0 reserves memory aggressively and doesn't free it.

From an initial 200MB memory footprint, taking 10 small JPEG images, cropping and resizing them grows memory usage to 400MB. These are orders of magnitude higher than what memory usage should be.

What's worse, the memory isn't being freed either. After around 150 images my server runs out of memory at 8GB.

Go profiling only indicates 3.2MB being used which hints that the C memory allocations aren't being freed by govips. I recently added debugging to show created and closed imagerefs and these also indicate that Go garbage collection is successfully calling the govips close() function for each image.

This likely means the govips close() function is ineffectual and doesn't actually free the memory.

Running valgrind/massif on fastgallery indicates that vips mallocs are indeed at fault. Please see the issue I raised with upstream with C memory profiling dumps: https://github.com/libvips/libvips/issues/1929

I'm awaiting for guidance upstream guidance from John Cupitt on how to further debug. Any input is warmly welcome from @Elad-Laufer @davidbyttow @vansante @bozaro or other contributors who might have ideas.

**Comment by vansante** [comment]
I did some testing before and after, and it appears my MR has introduced this, so I propose reverting that MR for now.

https://github.com/davidbyttow/govips/pull/137

I thought the go memory  management would take care of the memory but I was mistaken, my apologies.

**Comment by tonimelisma** [comment]
Thanks - no worries. Sounds like I should write a unit test to check for memory leaks!!
