### ISSUE TITLE
Question about concurrent usage

### ISSUE THREAD

**Issue by sachinwalia2k8** [davidbyttow/govips#14]
Thanks for the amazing VIPS binding. This is something I've been looking for. I am trying to build this as a microservice and have a questions in terms of the lifecycle of VIPS. I see that in some of the example following statements are present:
	vips.Startup(nil)
	vips.Shutdown()

My question is that this must be done per http request or once during the server startup/shutdown?

Moreover I am wondering if you have some benchmark comparing this with "sharp" (https://github.com/lovell/sharp) or "bimg" (https://github.com/h2non/bimg). I understand it may not be a 1:1 comparison but it'd be nice to see some numbers.

thanks.

**Comment by davidbyttow** [comment]
Hi, Yes, I've used this quite extensively. It is faster than sharp but I have not tested against bimg. I will get to this at some point.

And no, you do not do startup/shutdown per request, it's done per server startup/shutdown. You shouldn't have to worry about anything else if you use the API directly (it will handle thread cache clearing, etc)

**Comment by sachinwalia2k8** [comment]
thanks. Will likely explore your library in upcoming weeks.

**Comment by KevinColemanInc** [comment]
I compared compressing 3 jpeg images (a 20Mb, a 100x100, and 1 mid-size jpegs) with govips and [h2non/bimg](https://github.com/h2non/bimg). bimg was faster (by 50-10%) and had slightly more compression.
