### ISSUE TITLE
Package not working on Windows

### ISSUE THREAD

**Issue by baraklevy20** [davidbyttow/govips#141]
It seems like the package doesn't work on Windows due to using a `/tmp` path, which doesn't exist on Windows.
https://github.com/davidbyttow/govips/blob/6ab8806cfd1f17677837d9f62ef850c7f5ca8cd4/vips/icc_profiles.c#L646

Calling `vips.Startup(nil)` on Windows fails with the errors
```
failed opening file for writing: /tmp/srgb_v2_micro.icc
failed opening file for writing: /tmp/sgray_v2_micro.icc
failed opening file for writing: /tmp/srgb_iec61966_2_1.icc
failed opening file for writing: /tmp/generic_gray_gamma_2_2.icc
```

I managed to temporarily solve it by changing the path to a valid Windows path e.g.
```
char *SRGB_V2_MICRO_ICC_PATH = "C:\\temp\\srgb_v2_micro.icc";
```

**Comment by tonimelisma** [comment]
Hey @baraklevy20 thanks for the issue report.

Indeed, that's correct. We only talk about macOS and Ubuntu in the README, I think we would need to be more up front about Windows not being a fully supported platform. It's not a CI/CD target for us at the moment. I investigated the situation just a few weeks ago and at that stage the toolchain on native Windows was in such a state of disarray I didn't see it worth the effort to start setting up a CI/CD configuration for it. There's some issues where the topic has been discussed recently.

Regarding the issue you raised, we should probably be using ioutil.TempDir() to be cross-platform, that's a clear bug.

Other than that, before we have a CI/CD pipeline and clearly defined environment for Windows development we unfortunately will not attempt to find and fix Windows bugs.

If you want to use govips on Windows, the most practical approach is to use it via WSL. Would that work for you?

**Comment by tonimelisma** [comment]
@baraklevy20 unless of course you would be interested in contributing by setting up a Windows CI/CD pipeline that's robust? If so, I'd be more than happy to start maintaining Windows builds.

**Comment by tonimelisma** [comment]
Hey @baraklevy20 the bug's been fixed now and the temporary files should work on Windows. Please comment if there's any other bugs and/or you have interest in help setting up CI for Windows or providing guidance on a suitable environment.

**Comment by stackcoder** [comment]
I created a [minimal Docker container](https://gist.github.com/stackcoder/11629bd1e6712b5cb44c74d033e68ae4) to cross-compile govips for Windows using MinGW and MSYSY2. Maybe this is a good starting point to provide a CI pipeline.

**Comment by ugljesas** [comment]
I've been able to get govips working natively on windows with the following steps, posting here in case someone needs steps to set it up:

1. Install pkg-config, easiest way would probably be via choco:
choco upgrade -y pkgconfiglite
2. Download the static build for win64/32 from the official releases page

**Comment by mholt** [comment]
@ugljesas Thanks for writing this up, I feel like I'm 90% of the way there. It seems to compile, but I get linker errors. Did you encounter linker errors, and if so, how did you overcome them?

Specifically:

```
C:\Program Files\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/ProgramData/mingw64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/13.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lintl: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

According to my searching, `lintl` apparently means `libintl`, which is part of GNU `gettext`... apparently they have [Windows downloads](https://mlocati.github.io/articles/gettext-iconv-windows.html) but these don't contain any DLLs (and installing it did not solve the problem for me).

So I'm just wondering what step I'm missing -- I believe I did everything you described...

**Comment by mholt** [comment]
FWIW I had a bad MSYS2 environment or something like that... nuking it from orbit and reinstalling MSYS2, then reinstalling the packages like libvips, made my program's compilation work. :man_shrugging:
