### ISSUE TITLE
Rotate only supports multiples of 90 degrees

### ISSUE THREAD

**Issue by boosh** [davidbyttow/govips#148]
The `Rotate` method wraps vips' `rot` function, which according to [the docs](http://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-rot):

> Rotate in by a multiple of 90 degrees.
> Use vips_similarity() to rotate by an arbitary angle. vips_rot45() is useful for rotating convolution masks by 45 degrees. 

Actually, there is a [vips_rotate](http://libvips.github.io/libvips/API/current/libvips-resample.html#vips-rotate) function which also takes an arbitrary angle. I started working on a PR but I think the right thing to do would be to refactor the current `Rotate` function to wrap vips_rotate instead of vips_rot. However this would require changing `Angle` to be a double instead of an int, so it'd be a breaking change to the API.

**Comment by tonimelisma** [comment]
Hey @boosh. We've just upgraded to 2.x so it's not feasible to do API breaking changes at the moment. But that's no problem, we can just add another Rotate function with a different name that would accept float arguments. Maybe RotateFree or RotatePrecise or something similar?

A PR would be greatly appreciated if you could spare the time!

**Comment by boosh** [comment]
OK cool. In that case I'll try my hand at adding support for `vips_similarity` since a) it offers something new and b) it avoids having to think of what to call another rotation function. I'm no C maestro but I'll see how I get on.

**Comment by boosh** [comment]
Closed by #149
