### ISSUE TITLE
imageRef.Bands() returns unlikely number 5376256 for all images

### ISSUE THREAD

**Issue by norbertvannobelen** [davidbyttow/govips#154]
I have been porting over my code from v1 to v2 to get the alpha channel addition into my code instead of having to call onto the libvips cli.

In this I am stuck at:

```
	imageref, _ := vips.NewImageFromFile("png-24bit.png") // Image from the test resources
	log.Printf("bands: %d", imageref.Bands)
```

giving consistently 5376256 bands for all images, which is unlikely....

Libvips used from Alpine edge (Dockerfile included for replication purposes)

```
FROM alpine:edge
RUN apk add go=1.15.6-r0 ca-certificates git build-base openssh bash tzdata

RUN apk update && apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community \
    vips-tools vips-dev fftw-dev glib-dev php7-dev php7-pear build-base ca-certificates exiftool 
```

Vips version:

```
/go/src/build # vips -v
vips-8.10.5-Fri Dec 18 10:14:09 UTC 2020
```

And from the test program govips init:

```
2021/01/04 04:33:34 [govips.info] vips 8.10.5 started with concurrency=1 cache_max_files=0 cache_max_mem=52428800 cache_max=100
```

Govips version latest tested version:

v2.3.2-0.20210103172426-e31893b02410

Also tested with 2.3.1: Same results

My guess is that the problem is in a header file mismatch: What version of libvips should be used for compatibility with govips>

**Comment by tonimelisma** [comment]
This is interesting. The CI environments are all Ubuntu LTS versions as well as last two macOS versions which both seem to use 8.10.2. Is it possible you test it with that?

Are you aware of any upstream changes which might be affecting this?

What if you turn debug messages on via using vips.LoggingSettings(nil, vips.LogLevelDebug)? And any tracing you can add to vips init() config?

**Comment by norbertvannobelen** [comment]
Sorry, was away for a few days.

I found the issue: I was logging ```imageRef.Bands``` instead of imageRef.Bands(). 

The bug I am trying to chase however stays the same (I thought I have found the root cause with the bands), I will refile that one with a correct description.
