### ISSUE TITLE
vips_insert function on Govips

### ISSUE THREAD

**Issue by amalbala** [davidbyttow/govips#171]
Hi,

Could be possible use `Insert` with Govips? I am porting a python code that uses this function but I can not find any similar function in govips.

https://libvips.github.io/libvips/API/current/libvips-conversion.html#vips-insert

Nice work!

**Comment by tonimelisma** [comment]
Hey @amalbala! Thanks for the feature request. For sure, insert would be a welcome addition for govips.

Do you think you would be able to contribute a PR? There's plenty of great examples if you check recently closed PRs such as:

https://github.com/davidbyttow/govips/pull/162

https://github.com/davidbyttow/govips/pull/160

https://github.com/davidbyttow/govips/pull/153

https://github.com/davidbyttow/govips/pull/152

How do you feel, do you have time and energy to whip up one based on those examples?

**Comment by tonimelisma** [comment]
Hey @amalbala vips_insert is now supported via the latest merge!
