### ISSUE TITLE
Please update https://launchpad.net/~tonimelisma/+related-packages ppa packages

### ISSUE THREAD

**Issue by bozaro** [davidbyttow/govips#179]
Last week released https://github.com/libvips/libvips/releases/tag/v8.10.6 with multiple fixes.
Current PPA is 8.10.2

**Comment by tonimelisma** [comment]
Hey @bozaro. To keep the build stable we don't update to each patch version from source. The PPA is maintained based on the latest stable Ubuntu source packages. I'll update the PPA when Ubuntu 21.04 seems ready to release, probably in the coming days or weeks. It seems like it will ship with 8.10.5. Next update after that will be in October when Ubuntu 21.10 releases, with whatever libvips version they'll pick from Debian unstable at that time.

If you want to create your own PPA with the latest libvips packages, you can use my Docker builds at https://github.com/tonimelisma/libvips-dev-tonimelisma

The `within_container.sh` shows a script which does the actual building within the Docker environment.

In case you are not familiar with Debian packaging (which is complex and not very user friendly), I would just use that docker image and the latest Ubuntu source package. Then just replace the source with the latest libvips sources and build. You'll need to create your own GPG keys and Ubuntu PPA etc.

**Comment by tonimelisma** [comment]
Hey @bozaro I went ahead and updated both focal as well as bionic libvips packages to the hirsute version, 8.10.5. Hope that helps.
