### ISSUE TITLE
Export to JPEG/PNG and return it as []byte

### ISSUE THREAD

**Issue by psykomo** [davidbyttow/govips#18]
Hi, 

How can i export to or generate JPEG or PNG from *vips.ImageRef, and then return it as []byte? 

At the moment, the only way i know to get a JPEG/PNG image as []byte from a *vips.ImageRef is to first use vips.Jpegsave or vips.Pngsave and then read the generated file as []byte. 

Is there any other way? 

Apologize, if i'm not explaining my problem correctly.

Thanks!

**Comment by davidbyttow** [comment]
Hi, the Transform type's "Apply" method returns the bytes for the exported image. Does that work for you or do you need to do it via direct access to the image?

**Comment by psykomo** [comment]
Here is my case: I have 2 images that need to join. I use vips.Join to join them. It returns C.VipsImage. Now, how Can I export this joined image to jpeg/png and return it to the caller as []byte? Does transform support Join?

**Comment by davidbyttow** [comment]
Oh, I see. Sounds like I just need to make export a public method that you can use.

**Comment by davidbyttow** [comment]
OK, you should now be able to construct an ImageRef (which handles garbage collection) from a C.VipsImage, and a Transform from an ImageRef. So, something like this:

```go
image := vips.NewImageRef(joinedImage, vips.ImageTypeJPEG)
data, err := vips.NewTransform().Image(image).Apply()
```

Hope that helps

**Comment by davidbyttow** [comment]
Relevant commit: https://github.com/davidbyttow/govips/commit/7307f009ae77a858cf99d7f8d2a2cd16ba8ad012

**Comment by psykomo** [comment]
Thanks!
