### ISSUE TITLE
How to build for docker with alpine linux? 

### ISSUE THREAD

**Issue by Diden05** [davidbyttow/govips#185]
Subj

**Comment by tonimelisma** [comment]
Hey @Diden05! Thanks for using govips. You can find example Ubuntu docker files at https://github.com/tonimelisma/libvips-dev-tonimelisma

Unfortunately we don't have ready Dockerfiles for alpine linux, but pulling in the libvips development package should bring in the multitude to other graphics libraries (libjpeg, libheif, etc) it is linked to. Naturally you need all the C and Go build dependencies as well.

**Comment by EverWinter23** [comment]
Hey, I did take a look at the Dockerfiles made with `Ubuntu:20.04` as the base image. However, ideally you'd want to keep your container size as small as possible. I took a look at other alpine images such as this [one](https://github.com/ishaanbahal/golang-alpine-vips/blob/master/Dockerfile), but I keep running into the following errors:

```bash
handlers.go:37:32: undefined: vips.NewDefaultExportParams
internal/api/server.go:14:3: undefined: vips.Startup
internal/api/server.go:15:9: undefined: vips.Shutdowninternal/api/handlers.go:37:32: undefined: vips.NewDefaultExportParams
internal/api/server.go:14:3: undefined: vips.Startup
internal/api/server.go:15:9: undefined: vips.Shutdown
```

Any ideas? I'm trying to use `libvips`, and ofcourse `govips` with the base image as `golang-alpine`.

**Comment by tonimelisma** [comment]
Looks like your Go code can't find the Govips library. I suggest opening a terminal inside the container and ensuring you can run ```go get``` to install Govips in the first place etc

**Comment by EverWinter23** [comment]
Dockerfile with `alpine` as base

```Dockerfile
FROM golang:1.14-alpine3.13

RUN apk add musl-dev vips-dev gcc

WORKDIR /src
COPY . .
RUN go build -o /bin/app /src/cmd/app/main.go
```
