### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by Andrewsville** [davidbyttow/govips#186]
Govips IMO currently supports exporting to JPEG, PNG, WebP, HEIF and TIFF. I would really like to see AVIF support.

From the outside it looks pretty straightforward. The go/c part will be easy, ppa:tonimelisma/ppa contains libaom so AVIF support should already be present in CI, at least in the Linux part. I have no idea about the MacOS part, but we'll see when we get there :)

Unless someone is already working on it, I should be able to prepare a PR in a week or two.

**Comment by tonimelisma** [comment]
Hey @Andrewsville! Thanks for the great suggestion. I agree wholeheartedly, AVIF support would be great. I checked the macOS homebrew version of libvips and it seems to support AVIF via libheif if I understand correctly.

In any case a PR would be greatly welcome! Looking forward to the contribution. Thanks again!
