### ISSUE TITLE
How to set white background with 	NewJpegExportParams()?

### ISSUE THREAD

**Issue by 9mm** [davidbyttow/govips#194]
Hey, I'm simply converting PNG to JPG, and I would like to make all backgrounds default to `white` instead of `black`.

I'm just wondering how I do this.

```
inputImage, err := vips.NewImageFromFile(filePath)
ep := vips.NewJpegExportParams() 
ep.Quality = 100                 
imageBytes, _, err := inputImage.ExportJpeg(ep)
```

**Comment by 9mm** [comment]
I asked here although he says it's not supported. I see some stuff in the source code about backgrounds though, is it just named something else?

https://github.com/libvips/libvips/discussions/2242#discussioncomment-706270

**Comment by tonimelisma** [comment]
Hey @9mm just use the Flatten function to remove the alpha layer and replace it with a background colour first:
https://pkg.go.dev/github.com/davidbyttow/govips/v2@v2.5.0/vips#ImageRef.Flatten
