### ISSUE TITLE
Make it possible to manually call ImageRef.Close again

### ISSUE THREAD

**Issue by rafaelsierra** [davidbyttow/govips#195]
I understand that the reasoning is to leave all memory management to the garbage collector, however when performing too many operations in parallel too fast, GC will not run fast enough to free enough memory.

I found this running a load test on my server and with the default `GOGC` it quickly explodes in memory usage and crashes out of memory, however if I set it to a smaller value, like `10` then way more requests can go through before the memory gets exhausted.

Keep in mind this happens behind a semaphore allowing only 10 simultaneous operations, so it is not a matter of just doing too much operations, but rather that memory grows faster than GC can release.

So if we can manually call `.Close` after each operation I believe we won't have this issue anymore

**Comment by tonimelisma** [comment]
Hey @rafaelsierra thank you so much for the mindful and well argued issue. I've actually had the exact same issue myself and have resorted to manually garbage collecting stuff and even had to refactor my program to restart goroutines to speed up the garbage collection.

It doesn't hurt to have the option, and trying to close an already closed image doesn't hurt so I'll add it in later today.

Thank you very much for the contribution! Have a great weekend!

**Comment by tonimelisma** [comment]
@rafaelsierra this is fixed, pushed out v2.6.0 release out just now. Thank you again!
