### ISSUE TITLE
Regression in animated GIF sizes

### ISSUE THREAD

**Issue by vansante** [davidbyttow/govips#196]
Prior to #192 this library returned the right image width of the image, but after this PR the returned image size seems to be linked to the number of image frames (pages).

For instance, I have this image (sorry for the content, its my unittest image :sweat_smile: ) of 90x90 pixels:

![failgif](https://user-images.githubusercontent.com/582763/119661620-c2bff600-be30-11eb-9936-df2fe7e552b6.gif)

Previously when I opened this file with govips it would report `90` with the `Width()` function. Now it returns `810` which makes sense because there are 9 pages and 9 * 90 is 810.

However, I think this behaviour is incorrect, as every program will display the picture with 90 pixels width and I shouldn't have to divide by the amount of pages right?

I think the current way animated pictures is implemented is a bit iffy, as I want to just display a certain frame when I  want to create a jpeg thumbnail, instead of a strip of all frames in one image.

**Comment by tonimelisma** [comment]
@vansante for some reason I'm unable to replicate. Can you check the unit test I added in the latest commit, it seems to work at least on my Ubuntu computer: https://github.com/davidbyttow/govips/commit/e8128e50580a76a72880edd18fa3c0312d452a60

**Comment by vansante** [comment]
@tonimelisma Ive run your test and you are correct. I was wrong about the width, its the height that gets multiplied by the page size.

I've altered your unittest:

```golang
func TestImageRef_ImageSize(t *testing.T) {
	image, err := NewImageFromFile(resources + "gif-animated-2.gif")
	assert.NoError(t, err)
	width := image.Width()
	height := image.Height()
	assert.Equal(t, 90, width)
	assert.Equal(t, 90, height)
}
```

Which then outputs:
```
== RUN   TestImageRef_Width
2021/05/27 14:03:39 [govips.info] vips 8.10.6 started with concurrency=1 cache_max_files=0 cache_max_mem=52428800 cache_max=100
2021/05/27 14:03:39 [govips.info] registered image type loader type=tiff
2021/05/27 14:03:39 [govips.info] registered image type loader type=webp
2021/05/27 14:03:39 [govips.info] registered image type loader type=gif
2021/05/27 14:03:39 [govips.info] registered image type loader type=jpeg
2021/05/27 14:03:39 [govips.info] registered image type loader type=png
2021/05/27 14:03:39 [govips.info] registered image type loader type=svg
2021/05/27 14:03:39 [govips.info] registered image type loader type=heif
2021/05/27 14:03:39 [govips.info] registered image type loader type=heif
    image_test.go:856: 
        	Error Trace:	image_test.go:856
        	Error:      	Not equal: 
        	            	expected: 90
        	            	actual  : 810
        	Test:       	TestImageRef_Width
--- FAIL: TestImageRef_Width (0.00s)
```

**Comment by tonimelisma** [comment]
Thank you @vansante again for the valuable contribution. You're completely correct it seems. Looks like all of our automated tests run on non-animated images so they haven't catched any of these regressions.

I've gone and disabled the animation support again in the latest release. Before re-adding animation support, we need to ensure all of the existing functions work well with animations. Perhaps this would be best accomplished by writing short unit tests with animated gifs for all functions - does anyone have time to work at something like this?

@GordonWu apologies, please see above

**Comment by GordonWu** [comment]
@tonimelisma I also found this problem some time ago, and I will try to correct this part. But where I am currently, due to covid-19, there should be no way to deal with this problem so quickly. I am sorry about that.

**Comment by tonimelisma** [comment]
No worries @GordonWu - thanks for all the contributions have done and if/when you have time to contribute any more in the future, all work is greatly appreciated. Hope you have a great summer!
