### ISSUE TITLE
vips_image_new_from_memory

### ISSUE THREAD

**Issue by wessorh** [davidbyttow/govips#2]
I was hoping for an example on creating a image from a buffer where the buffer is just bytes and not a formatted image object in memory. The current implementation didn't seem to provide access to the vips_image_new_from_memory and vips_image_new_from_memory_copy functions.

Happy to develop the code if that is the suggested route and you take pull requests

thanks,

-rick

**Comment by davidbyttow** [comment]
Definitely take pull requests.

To be clear, the buffer is a simple RGBRGB... style array? If so, that makes sense. Typically most cases the image is in a predetermined format, but happy to expose this.
