### ISSUE TITLE
ImportParams missing  during LoadImageFromBuffer

### ISSUE THREAD

**Issue by dark-wind** [davidbyttow/govips#203]
I got error:
```
 value "0.000000" of type 'gdouble' is invalid or out of range for property 'dpi' of type 'gdouble'
```
when I load a pdf file with dpi params

## my code 
```
// init some params
pdfImportParams := vips.NewImportParams()
pdfImportParams.Density.Set(300)
pdfImportParams.Page.Set(0)
// get a file
buf, err := ioutil.ReadFile("foo.pdf")
checkError(err)
image1, err := vips.LoadImageFromBuffer(buf, pdfImportParams)
// write to jpg
ep := vips.NewJpegExportParams()
imageBytes, _, err := image1.ExportJpeg(ep)
err = ioutil.WriteFile("bar.jpg", imageBytes, 0644)
checkError(err)
```
the "Density(dpi)" didn't work

## My goal
pdf to jpg with dpi params
such as
```sh
vips pdfload foo.pdf bar.jpg --dpi=300 --page=1
```
## bug point
```
if err := C.load_from_buffer(&importParams, unsafe.Pointer(&src[0]), C.size_t(len(src))); err != 0 {
     return nil, ImageTypeUnknown, handleImageError(importParams.outputImage)
}
```
this code located in "vips/foreign.go" line 253

I am new to both Libvips and Golang, I don't know how to lock and fix this problem

**Comment by dark-wind** [comment]
I used the VIPS library from C to solve it:
```
double dpi = (gdouble)300;
    vips_pdfload("41FC0026.pdf",&out,"dpi",dpi,NULL);
```

I hope this code helps fix the bug

**Comment by tonimelisma** [comment]
Thanks so much for the bug report @dark-wind! This is valuable work.

Would it be too much to ask if you could provide a PR? Any contributions are greatly appreciated! If not, I will try and take a look at this at some stage although I'm now on summer vacation so it might take a bit of time.

**Comment by ugljesas** [comment]
Thanks for the fix!

Do you maybe have an estimate of when this will end up in a stable release? I'm currently using the version tied to the commit of the fix, and everything seems to be alright but would prefer to switch to a stable version before this goes to production.

**Comment by davidbyttow** [comment]
sure, we can do a release, i think

**Comment by davidbyttow** [comment]
Done @ugljesas https://github.com/davidbyttow/govips/releases/tag/v2.11.0

**Comment by ugljesas** [comment]
Amazing, thank you!
