### ISSUE TITLE
foreign.c warnings 

### ISSUE THREAD

**Issue by slav123** [davidbyttow/govips#204]
Is there any way to disable warnings during compilation ?

```# github.com/davidbyttow/govips/v2/vips
foreign.c:195:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
foreign.c:208:1: warning: non-void function does not return a value [-Wreturn-type]
```

**Comment by tonimelisma** [comment]
Yeah there is. I'm currently on summer vacation, any chance you could look at producing a PR for the topic? The fix shouldn't be complicated, just clean up the C code a bit. Thanks for reporting this @slav123 !
