### ISSUE TITLE
Is there a way to supply an ICC profile to embed in an image?

### ISSUE THREAD

**Issue by AttilaTheFun** [davidbyttow/govips#205]
I would like to be able to supply my own ICC profile to use when writing an image, e.g. one of these:
https://github.com/saucecontrol/Compact-ICC-Profiles

I see that there is an API to detect if an image *has* an ICC profile, and I understand that the library attempts to preserve existing ICC profiles, but I was wondering if I could use govips to embed one of these profiles in an image that does not have one.

**Comment by tonimelisma** [comment]
Hey @AttilaTheFun! Unfortunately no, not at the moment. Upon initialisation, vips creates optimised default ICC profiles in a temporary directory which are used for images that don't have one: https://github.com/davidbyttow/govips/blob/master/vips/icc_profiles.go

OptimizeICCProfile() is found on row 1002 here https://github.com/davidbyttow/govips/blob/master/vips/image.go

It wouldn't be too difficult to add the functionality. If you would want to submit a PR we would gladly merge it!

**Comment by AttilaTheFun** [comment]
Hi @tonimelisma, I finally had some time to open a PR to add support for transforming ICC profiles. Would you like to reopen this issue and take a look?

https://github.com/davidbyttow/govips/pull/208
