### ISSUE TITLE
Gifs break when being imported / exported

### ISSUE THREAD

**Issue by AttilaTheFun** [davidbyttow/govips#209]
I'm trying to use govips to handle normalizing images uploaded to my web server. Everything seems to be working well for non-gif images, but gifs do not round trip. Gifs that have been read into memory and then written back out to a file seem to only include the first frame.

Here you can see my testing code which I used to reproduce the bug as well as the working input and broken output gifs.

| Input | Output |
| ----- | ----- |
| <img src="https://user-images.githubusercontent.com/3255391/130739757-b6665587-75dc-4179-8950-9e45059ae7a5.gif"> | <img src="https://user-images.githubusercontent.com/3255391/130739773-d3252aa6-acc6-4655-aa48-8e440facd97a.gif"> |

Is this a bug? Or am I holding it wrong? Any help would be appreciated!

Code to reproduce the issue:
```
package image

import (
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"testing"

	"github.com/davidbyttow/govips/v2/vips"
)

func TestReproduceGIFBug(t *testing.T) {

	// Open the input file:
	inputFilePath := filepath.Join(testImagesFolder, "Input.gif")
	inputFile, err := os.OpenFile(inputFilePath, os.O_RDWR, 0777)
	if err != nil {
		t.Fatal(err)
	}
	defer inputFile.Close()

	// Read the input file:
	inputBytes, err := ioutil.ReadAll(inputFile)
	if err != nil {
		t.Fatal(err)
	}

	log.Printf("Input bytes: %v", len(inputBytes))
	log.Println()

	// Create a vips image:
	img, err := vips.NewImageFromBuffer(inputBytes)
	if err != nil {
		t.Fatal(err)
	}

	// Export the gif:
	ep := vips.NewGifExportParams()
	outputBytes, _, err := img.ExportGIF(ep)
	if err != nil {
		t.Fatal(err)
	}

	log.Printf("Output bytes: %v", len(outputBytes))
	log.Println()

	// Delete the file at the file path if a file exists:
	outputFilePath := filepath.Join(testImagesFolder, "Output.gif")
	if _, err := os.Stat(outputFilePath); !os.IsNotExist(err) {
		err = os.Remove(outputFilePath)
		if err != nil {
			t.Fatal(err)
		}
	}

	// Open the file for reading / writing:
	outputFile, err := os.OpenFile(outputFilePath, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0777)
	if err != nil {
		t.Fatal(err)
	}
	defer outputFile.Close()

	// Write the output file:
	outputFile.Write(outputBytes)
}
```

**Comment by tonimelisma** [comment]
Hey @AttilaTheFun I think they are but it's a bit more complicated. There's an existing issue #117 if you check that? Closing this as a dupe, if that's alright?

**Comment by GordonWu** [comment]
Hi @AttilaTheFun  you can pull newest govips from master branch, It should be support for loading parameters(by David Byttow) and then you can load all page of gif file just like that.



	intSet := vips.IntParameter{}
	intSet.Set(-1)

	params := vips.NewImportParams()
	params.NumPages = intSet

	oriImg, err := vips.LoadImageFromBuffer(dataByte, params)
	if err != nil {
		logs.Error(err.Error())
		return nil, err
	}
	defer oriImg.Close()


but just like @tonimelisma comment say, if currently govips need to fully support animation gif need a lots of work to do.
