### ISSUE TITLE
Resized image file size 20% to 40% larger than "sharp" of Node.js

### ISSUE THREAD

**Issue by sann1918** [davidbyttow/govips#21]
govips produces 20% - 40% larger image file sizes than sharp (node equivalent) does for the same image dimensions and the same Lanczos3 kernel. 

Please check if govips is producing the optimal file size since both are using the same libvips backend.

Thanks.

**Comment by davidbyttow** [comment]
Interesting, thanks for that. Can you give an example image or is it consistent across all images?

**Comment by sann1918** [comment]
It's resizing ordinary iPhone photo images. Photos are 4K, 14 ~ 17 MB each. After running 20 photos, around 10 photos have "the larger image size issue". If you need one image, please let me know how to get it to you. It's 17 MB.

**Comment by sann1918** [comment]
David, I found your gmail on Medium. Just sent you the original image and the resized ones. One by govips and the other by sharp. 

the original 15 MB (4032 x 3024).
govips produces a 1.3 MB file (806 x 605)
sharp produces a 877KB file (806 x 605)

Please check gmail and let me know if you need more info.

**Comment by davidbyttow** [comment]
Looking at this now

**Comment by davidbyttow** [comment]
Hey @sann1918, can you show me your sharp code? I'm resizing like this but getting 1.3MB, which is the same as VIPs

```
sharp = require('sharp');

sharp('onions.png')
  .resize(806, 605)
  .toFile('onions-sharp.png');
```

**Comment by sann1918** [comment]
I double checked. The results is 877 KB. 

This is the code just ran on node v8.9.3 on the latest macOS 

```javascript
const fs = require('fs');
const sharp = require('sharp');

fs.readdir('./images/', (err, files) => {
    files.forEach(file => {
        sharp('./images/' + file)
            .resize(806, 605)
            .toFile('./resized/' + file);
    });
});
```

**Comment by devmarco** [comment]
Any update on that?

I'm resizing an image to 900/900, converting to `TIFF` with quality=100

```
vips.NewTransform().
    LoadBuffer(imageBody).
    Resize(900, 900).
    Format(vips.ImageTypeTIFF).
    Quality(100).
    StripMetadata().
    OutputBytes().
    Apply()
```

The generated image has the size of `2.5mb`, and the same file generated using Sharp (Nodejs version) has `852kb`, its a huge difference

**Comment by tonimelisma** [comment]
Hey @devmarco and @sann1918 apologies for the delays. We're now cleaning up govips, we've integrated a bunch of new functionality and bug fixes. I'll try to reproduce this with the latest when I have the time.

Is it possible you attach to this issue any sample images you've used?

**Comment by tonimelisma** [comment]
I've replicated the bug somewhat. Creating a 100-quality TIFF in sharp and govips produce file sizes of 2.0 and 3.8 MB respectively.

Code samples:

<pre>
package main

import (
	"fmt"
	"io/ioutil"
	"os"

	"github.com/davidbyttow/govips/v2/vips"
)

func checkError(err error) {
	if err != nil {
		fmt.Println("error:", err)
		os.Exit(1)
	}
}

func main() {
	vips.Startup(nil)
	defer vips.Shutdown()

	image1, err := vips.NewImageFromFile("input.jpg")
	checkError(err)
	defer image1.Close()

	err = image1.AutoRotate()
	checkError(err)

	fmt.Println(image1.Height(), image1.Width())
	err = image1.Resize(0.5, vips.KernelAuto)
	checkError(err)
	fmt.Println(image1.Height(), image1.Width())

	ep := vips.NewDefaultExportParams()
	ep.Format = vips.ImageTypeTIFF
	ep.Quality = 100
	image1bytes, _, err := image1.Export(ep)
	err = ioutil.WriteFile("output.tiff", image1bytes, 0644)
	checkError(err)
}
</pre>

<pre>
const sharp = require('sharp');

sharp('input.jpg')
    .rotate()
    .resize(972, 1296)
    .tiff({
        quality: 100
    })
    .toFile('sharp.tiff');
</pre>

**Comment by davidbyttow** [comment]
That's quite a difference... will investigate.

**Comment by davidbyttow** [comment]
Turns out that sharp was adding compression by default (outside of the quality value). I've changed govips to do the same, along with some TODOs to control this: https://github.com/davidbyttow/govips/pull/146
