### ISSUE TITLE
Add support for vips ICC transform API

### ISSUE THREAD

**Issue by AttilaTheFun** [davidbyttow/govips#210]
I'd like to use the vips_icc_transform API through govips - I asked about this previously and was told I could open a PR.
I've got it working in a branch and made a pull request here: https://github.com/davidbyttow/govips/pull/208
Could you take a look and let me know if you have any feedback?

**Comment by Elad-Laufer** [comment]
This can be closed, no?

**Comment by AttilaTheFun** [comment]
@Elad-Laufer Yeah we can close this!
