### ISSUE TITLE
JPEGs failing to save with error: jpegsave_buffer: no property named `subsample_mode'

### ISSUE THREAD

**Issue by AttilaTheFun** [davidbyttow/govips#211]
I just deployed my images service today and now when calling img.Export with jpeg params is throwing an error:
```
		// Export a jpeg:
		ep := vips.NewDefaultJPEGExportParams()
		bytes, _, err := img.Export(ep)
		if err != nil {
			return nil, err
		}
```
Error:
```
 jpegsave_buffer: no property named `subsample_mode'
```

Weirdly, I can't reproduce this in a Go test locally - it only fails in a docker container on my server.

The relevant parts of my docker file are:
```
FROM golang:1.16-alpine as builder

# Install packages:
RUN apk update && \
    apk add pkgconfig git musl-dev vips-dev gcc

# Resolve the buildtime arguments:
ARG GITHUB_URL

# Configure git:
RUN git config --global url.${GITHUB_URL}.insteadOf "https://github.com/"
RUN go env -w GOPRIVATE=github.com/attilathefun

# Work in the /app/server directory:
WORKDIR /app/server

# Copy over the go module files and download the deps so they can be cached:
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the application directory and build the executable:
COPY ./app ./app
RUN GOOS=linux GOARCH=amd64 \
    go build \
    ./app/main.go

# FROM scratch
FROM alpine

# Install libvips:
RUN apk update && \
    apk add vips-dev

# Copy our static executable.
COPY --from=builder /app/server/main /app/server/main

# Set the entrypoint:
ENTRYPOINT /app/server/main

```

Do you know why this would fail in the docker container but not on my local machine? Are there some dependencies I'm missing on alpine linux? Thanks!

**Comment by tonimelisma** [comment]
It's probably the libvips version in the container. Use a more recent version

**Comment by AttilaTheFun** [comment]
Cool! I'm traveling this week but I'll try that out when I get back.

**Comment by AttilaTheFun** [comment]
@tonimelisma After a bit of struggling, I figured out I had to update to a newer Alpine Linux version (3.14) because I guess the older version (3.12) was pinned to an older version of vips-dev. Once I updated to 3.14, it installed vips 8.10.6 which seems to work. Thanks!
