### ISSUE TITLE
Support for Affine transform?

### ISSUE THREAD

**Issue by bakkerme** [davidbyttow/govips#212]
Hello! I was looking at using the affine transform function and found that while it's exposed via the [C bridge](https://github.com/davidbyttow/govips/blob/master/vips/resample.c#L13), it doesn't seem to be exposed as a Go function.
Are there any plans to make this happen? Would a PR for this require any in-depth knowledge of libvips? Thank you.

**Comment by tonimelisma** [comment]
@bakkerme Hey and welcome to the community! We don't really have a specific roadmap for Govips functions, we typically implement individual functions as requests come along.

I don't think any in-depth knowledge is required. If you look at past PRs, there's dozens of PRs implementing individual Libvips functions so there's a lot of examples you can look at. Also include unit tests as well as golden image tests in your PRs to ensure it works as expected. Nothing more than that.

If you have time and energy to submit a PR I would be very grateful!

Have a great week!
