### ISSUE TITLE
Add method to modify exif data

### ISSUE THREAD

**Issue by stackcoder** [davidbyttow/govips#214]
Expose the `vips_image_set`, `vips_image_get` [functions](https://www.libvips.org/API/current/libvips-header.html#vips-image-set) to the go world.

**Comment by tonimelisma** [comment]
Hey @stackcoder thanks for opening the issue. Can you clarify whether this is a feature request or whether you'd be up for creating a PR yourself? There's several other recent pull requests which expose new vips functions in an idiomatic way, they should provide good examples if you have the time.

**Comment by stackcoder** [comment]
It's only a feature request right now. I was looking for something like the `withMetadata` function implemented in [sharp](https://sharp.pixelplumbing.com/api-output#withmetadata).

**Comment by AttilaTheFun** [comment]
@tonimelisma @stackcoder +1 on this - I'd love to be able to read and write EXIF data with this library as well.

**Comment by tonimelisma** [comment]
I feel like EXIF data manipulation is a bit outside of the functionality libvips has. Thus I'd deem it also outside the scope of govips. I'm sure there are other golang libraries to manipulate EXIF data, even though I understand that it would be useful to have the functionality in the same library.

**Comment by AttilaTheFun** [comment]
@tonimelisma that's totally fine -- now that I have the APIs to extract blobs, I'm pulling out the EXIF and XMP data and using other libraries to parse that.
