### ISSUE TITLE
Looking for any optimisation in Export

### ISSUE THREAD

**Issue by rishavbhowmik** [davidbyttow/govips#215]
I was just trying to compare this mod, with NodeJS package [sharpjs](https://sharp.pixelplumbing.com/api-resize#resize), which is also a libVIPS binding.

While exporting the final output as buffer (any format jpeg, png, web), govips was taking significantly more time, about 200% extra.

My Golang code

```go
	vips.Startup(nil)
	defer vips.Shutdown()

	wingImageData, err := loadWingImage()
	if err != nil {
		panic(err)
	}

	var processTime int64 = 0

	resizeToTest := func(scale float64) {
		startTime := time.Now().UnixMilli()
		image, _ := vips.NewImageFromBuffer(wingImageData)
		image.Thumbnail(int(4290*scale), -1, vips.Interesting(vips.AlignCenter))

		outputImageData, _, err := image.Export(vips.NewDefaultWEBPExportParams()) // this is taking too long, about 200ms average

		if err != nil {
			panic(err)
		}
		endTime := time.Now().UnixMilli()
		processTime += endTime - startTime
	}

	for i := 1; i <= 10; i++ {
		resizeToTest(0.1)
		resizeToTest(0.2)
		resizeToTest(0.3)
		resizeToTest(0.4)
		resizeToTest(0.5)
	}

	println("Total time: ", processTime)
```

```output
$ go build .
$ ./m
Total time:  12627ms
```

Relative code in NodeJS

```js
const sharp = require("sharp")

const wingImageData = await loadImageBuffer(IMAGE_PATHS["wing.jpg"])

    var processTime = 0

    const resizeImage = async (scale) => {
        const sharpImage = sharp(wingImageData)
        const startTime = Date.now()
        const resizedImage = await sharpImage.resize({
            height: 4290 * scale,
        })
       .webp()
       .toBuffer()  // complets in 80ms average
        const endTime = Date.now()
        processTime += endTime - startTime
    }

    for (let i = 1; i <= 10; i++) {
        await resizeImage(0.1)
        await resizeImage(0.2)
        await resizeImage(0.3)
        await resizeImage(0.4)
        await resizeImage(0.5)
    }

    console.log(`Total time: ${processTime}ms`)
```

Output:
```
$ node .
Total time: 5817ms
```

And please note, I have tested the time consumed in resizing, whether I use Thumbnail or resize with scale, they don't take any significant time. Most of the time is being spent during export.

```
vips version: 8.11.4
go binding: github.com/davidbyttow/govips/v2 v2.7.0
```

Is there anything I should do to reduce the export time? 

Thank You

**Comment by tonimelisma** [comment]
Hey @rishavncopilot thanks for the issue. I think more profiling is required to understand where and why the export function is slowing things down. After all, you are comparing two completely different programming languages and libraries. I don't have a good guess right now from my behalf on where the hold-up might be in govips, unfortunately.

**Comment by luongngocminh** [comment]
I'm still facing this problem, feels like it shouldn't take that long to export a single image

**Comment by tonimelisma** [comment]
Hey @luongngocminh thank you for the comment. Do you think you might be able to put a bit of time into profiling and debugging to understand where the difference might come from?

**Comment by rishavbhowmik** [comment]
@tonimelisma I tried looking into code of both the projects.

The mechanism both codes are following are very different, so I couldn't do any comparative profiling.

However,

In SharpJS, works with [stream](https://nodejs.org/api/stream.html#stream), which essentially eliminates the need to copy buffer multiple times along the flow. https://github.com/lovell/sharp/blob/a333b87f5ddab03dc669729af9f7744809e980e7/lib/output.js#L1116

And entire processing takes place in a single shot, in the C++ add-on.
https://github.com/lovell/sharp/blob/a333b87f5ddab03dc669729af9f7744809e980e7/src/pipeline.cc#L59

The buffer is collected only once processing is finished. https://github.com/lovell/sharp/blob/a333b87f5ddab03dc669729af9f7744809e980e7/lib/output.js#L1135

So I guess the difference in performance is an obvious one, based on different in mechanism.

**Comment by tonimelisma** [comment]
Thanks @rishavbhowmik. That kind of verifies my thoughts on where the differences come from. Changing how govips loads and transforms pictures would require a major refactoring of basically the entire library. Right now we don't have nearly enough capacity for a project like that and personally I don't think there's enough value there to justify investment. If you personally feel like you would have enthusiasm and time to think of something like that, please let me know! This kind of feedback is always interesting never the less, to consider how we might re-architect govips if we had the resources. For now I'll close the issue.

**Comment by cdane** [comment]
I couldn't duplicate the faster results @rishavncopilot showed using sharp.  

From what I can tell, govips and sharp uses the same export mechanism in Vips for jpeg. I made a binding for vips_jpegsave, exporting directly to file, to see if that was faster, it wasn't.

It seems like a Vips is a very fast image processor, with an output bottleneck. Or at least for outputing  jpeg files of a few megabyte. Could be @rishavncopilot was using different file sizes than me.
