### ISSUE TITLE
Don’t strip the color profile when stripping metadata

### ISSUE THREAD

**Issue by eelco** [davidbyttow/govips#216]
When using the generic `StripMetadata` option, vips strips all fields, also those that are technically not “meta” data, but a key part of the data such as the color profile. This seems by design in vips (https://github.com/libvips/libvips/issues/1026), but it would be great if GoVips would improve on this, or at least offer the option to do so.

**Comment by Elad-Laufer** [comment]
Did you try image.Ref.RemoveMetadata()?

You'll need to set the StripMetadata option on export(/import) to False.
