### ISSUE TITLE
Passing additional parameters to PDF loader

### ISSUE THREAD

**Issue by victorkt** [davidbyttow/govips#23]
I'm developing a tool that convert pages in a PDF file to JPEG images. I need a way to specify which page to load from the PDF using this library, but it seems it is not currently possible.

From the libvips documentation, there are some parameters that allow for you to select which page, number of pages, DPI, and scale when loading the PDF:
http://jcupitt.github.io/libvips/API/current/VipsForeignSave.html#vips-pdfload-buffer

Checking this repo code, apparently there is currently no way to use these parameters.

Is it possible to do that?

If not, would adding a new argument to the [`init_image`](https://github.com/davidbyttow/govips/blob/master/bridge.c#L8) containing all the possible optional parameters, and then passing it over to the `vips_pdfload_buffer` function be the right way to tackle this? We could allow using the additional parameters for all other image types as well.

Thanks

**Comment by davidbyttow** [comment]
I think we could create a whitelist of parameters that are "passed through" based on the target type is a reasonable approach.

**Comment by tonimelisma** [comment]
Hey @victorkt thanks for the request. We've now got a PR cooking up here: https://github.com/davidbyttow/govips/pull/111

**Comment by davidbyttow** [comment]
Fixed as of https://github.com/davidbyttow/govips/pull/166
