### ISSUE TITLE
VipsJpeg: Wrong JPEG library version: library is 62, caller expects 80

### ISSUE THREAD

**Issue by xellDart** [davidbyttow/govips#256]
HI, i got this error using red-hot 8 with go version go1.17.6 linux/amd64.

I have problem, When trying to manipulate jpeg files error occurs:

Wrong JPEG library version: library is 62, caller expects 80
I was trying to find where that library is istalled with:

# ldconfig -p | grep libjpeg
libjpeg.so.8 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so.8
libjpeg.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libjpeg.so
and

# whereis libjpeg
libjpeg: /usr/local/lib/libjpeg.a
phpinfo() shows:

libJPEG Version 6b 
in "gd" section

I alredy search all solutions, but none work, I call vips from c++ and is working, but on CGO this breaks.

**Comment by tonimelisma** [comment]
Looks like a problem with your environment, not a problem with govips? Closing for now. Apologies for the long delay in reply.
