### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by aitreya** [davidbyttow/govips#264]
Hi,
 I am unable to install the package i have installed all the dependencies.

I am currently using ubuntu 20.04

![image](https://user-images.githubusercontent.com/65647270/152696342-b9f68da2-8831-4e12-bc25-2948006eabd4.png)

My Go installation :

![image](https://user-images.githubusercontent.com/65647270/152696390-c886acce-1fc3-4cad-b832-270f7a5f9ab2.png)

**Comment by davidbyttow** [comment]
This looks like a version mismatch or breakage in latest version of libvips, maybe go back to a previously supported version?

**Comment by davidbyttow** [comment]
Actually, see https://github.com/davidbyttow/govips/issues/187
