### ISSUE TITLE
fatal error: vips/vips.h: No such file or directory

### ISSUE THREAD

**Issue by igorescobar** [davidbyttow/govips#27]
Hey there guys. I'm trying to make the command `go get -u github.com/davidbyttow/govips` to work but I keep getting this error:
<img width="773" alt="screen shot 2018-02-04 at 15 32 59" src="https://user-images.githubusercontent.com/24032/35779198-05f6b65c-09c1-11e8-9d7f-cbbb930d435f.png">

I looks that I have everything installed:
<img width="435" alt="screen shot 2018-02-04 at 15 34 00" src="https://user-images.githubusercontent.com/24032/35779201-12d7ad4a-09c1-11e8-9f7d-5c6697f258c7.png">

But somehow the compilation doesn't work. Any ideas what I can do in order to fix it?

**Comment by Nafanya** [comment]
@igorescobar Looks like you have vips library/headers not in the search path. What does
`$ pkg-config --libs vips` output?

**Comment by davidbyttow** [comment]
As Nafanya said, you should have installed libvips, brew install should handle it (if you're on a mac) otherwise you'll need to download and compile the source.

https://github.com/jcupitt/libvips
