### ISSUE TITLE
Get Exif Values

### ISSUE THREAD

**Issue by maggie-vegaa** [davidbyttow/govips#272]
Hi! 
Im trying to get the image metadata from *vips.ImageRef
I have used the response of ImageFields to get the keys for the metadata
I was wondering, how do i get the value? I have not seen any function to use. or what do you recomend to get exif from the image

Thanks so much

**Comment by tonimelisma** [comment]
Hey, you can get the orientation with ```GetOrientation()``` and check ```HasExif()``` or remove ```RemoveMetadata()``` the metadata but we don't have a data structure to get the EXIF as of now. It hasn't been a core use case for people, mostly EXIF management is automated and if people want to mangle EXIF they've used other tools. It's definitely not outside of the remit of ```govips```. I'd be happy to look at a PR, would you have interest in doing one?
