### ISSUE TITLE
Thumbnail() uses libvips' thumbnail_image instead of thumbnail

### ISSUE THREAD

**Issue by KararTY** [davidbyttow/govips#279]
I've been loading in images using NewImageFromBuffer, calculating height & widths to resize and then using Thumbnail() on it and I've noticed that the GIFs and WebP's don't get treated properly.

I was under the assumption that Thumbnail() is libvips' thumbnail() but I checked and it uses thumbnail_image().

https://github.com/davidbyttow/govips/blob/6433b6338529aaa80c750986bb04226b5fd2db26/vips/resample.go#L53-L62

I'm not sure if this is intentional, and would like to know how to proceed.

**Comment by herloncf** [comment]
Hey @KararTY, I see yo marked as closed. What was the resolution? Is there any other way?

**Comment by KararTY** [comment]
> Hey @KararTY, I see yo marked as closed. What was the resolution? Is there any other way?

This works well for us:
https://github.com/Chatterino/api/blob/master/pkg/thumbnail/thumbnail.go#L90-L130
