### ISSUE TITLE
How to replace color from the image ?

### ISSUE THREAD

**Issue by arinkverma** [davidbyttow/govips#28]
Hi experts
I am developing an image's border customization app on vips. Earlier its on image-magic. All the operations are being mapped from Image-magic to vips. 

But I am stuck at image replace operation. In Image-magic, I used to copy alpha channel to achieve the desired color. Is similar possible in govips? How I can use bandadd here in govips?

![1](https://user-images.githubusercontent.com/1556486/35800298-8a85dd94-0a8e-11e8-9284-bc83835c6d44.png)
![2](https://user-images.githubusercontent.com/1556486/35800300-8ab84464-0a8e-11e8-9683-906b3ca5ab70.png)
![3](https://user-images.githubusercontent.com/1556486/35800301-8ae47408-0a8e-11e8-92b8-15cd78d48185.png)
![4](https://user-images.githubusercontent.com/1556486/35800302-8b1398f0-0a8e-11e8-8435-99365e52efb2.png)

**Comment by tonimelisma** [comment]
Hey @arinkverma apologies for the delays in answers. Is the topic still relevant for you?

Perhaps you could ask upstream libvips how they would implement this. Happy to help translate that to govips functionality then. Makes sense?

**Comment by tonimelisma** [comment]
Apologies for the lack of hands-on guidance. Closing for now due to lack of response.

**Comment by roffe** [comment]
I'm stuck on something similar. trying to figure out how to replace a color in a image with some other. 

best examples i can find is https://github.com/libvips/libvips/issues/872 but not sure how to o about to get the equal, bandand and ifthenelse thing in go
