### ISSUE TITLE
Get image color depth

### ISSUE THREAD

**Issue by songjiayang** [davidbyttow/govips#280]
How can I get a image color depth,  sometime we need to check the image color depth is 8bit or 10bit.

**Comment by tonimelisma** [comment]
Hey @songjiayang you can set the depth on export parameters but other than that govips kind of manages the bit depth by itself. Would you be interested in contributing a PR for this? Please check the contributing guidelines in the main repo for tips (including unit tests!) or check any of the recently approved PRs.
