### ISSUE TITLE
invalid flag in pkg-config --cflags: -Xpreprocessor : packages.Load error

### ISSUE THREAD

**Issue by Delicious-Bacon** [davidbyttow/govips#288]
Cannot get the project with Govips to run.

My `go.mod` keeps reporting the error:
`err: exit status 1: stderr: go build github.com/davidbyttow/govips/v2/vips: invalid flag in pkg-config --cflags: -Xpreprocessor
: packages.Load error`

Here are relevant outputs...

`go.mod`: 
```
require (
    `github.com/davidbyttow/govips/v2 v2.11.0`
)
```

`go env`:
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build302739192=/tmp/go-build -gno-record-gcc-switches"
```

`brew install vips pkg-config`:
```
Warning: vips 8.12.2_2 is already installed and up-to-date.
To reinstall 8.12.2_2, run:
  brew reinstall vips
Warning: pkg-config 0.29.2_3 is already installed and up-to-date.
To reinstall 0.29.2_3, run:
  brew reinstall pkg-config
```

`sudo apt -y install libvips-dev`:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libvips-dev is already the newest version (8.12.1-1build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I have done the `export CGO_CFLAGS_ALLOW="-Xpreprocessor"` but it doesn't help.

<hr>

EDIT

Now I also get `could not import C (cgo preprocessing failed) (compile)` and `go list failed to return CompiledGoFiles. This may indicate failure to perform cgo processing; try building at the command line. See https://golang.org/issue/38990.` along with 92 other problems relating to Vips.

**Comment by tonimelisma** [comment]
Hey @Delicious-Bacon did you ever figure this out? Did you find out the problem? I don't think we've had anyone else have this problem. Sounds like it's something related to your environment.

**Comment by Delicious-Bacon** [comment]
Hello @tonimelisma !

It disappeared in one of my projects, but whenever I use it in a new project, it keeps coming back.

I also have this error now:
```
# github.com/davidbyttow/govips/v2/vips
cgo: C compiler "gcc-5" not found: exec: "gcc-5": executable file not found in $PATH
```

But I have gcc, on `brew install gcc`:
```
Warning: gcc 11.3.0_2 is already installed and up-to-date.
To reinstall 11.3.0_2, run:
  brew reinstall gcc
```

**Comment by Delicious-Bacon** [comment]
What finally worked is the following:

1. Uninstall Homebrew:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
```

2. Remove any leftovers:

```
sudo rm -rf /home/linuxbrew
```

3. Install Homebrew:

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
**WARNING**
After installation, it was OK to set the path for `brew` following the instructions after the installation, but **NOT OK** to do `brew install gcc` as suggested by the brew installation script! If I ran `brew install gcc` and then `brew install vips`, the installation would result in the errors above. Does `vips` get gcc from some specific source? Is this reproducible?

4. Install vips (read note* on vips installation below):

```
brew install vips
```
This would install it normally, and I could use it in my Go projects.

NOTES

- Vips installation*—I had to set `ulimit -n 4096` since the default 1024 open files is too little for the whole vips installation.

- I also set the `export CGO_CFLAGS_ALLOW="-Xpreprocessor"` in my `/etc/profile`.

**Comment by tonimelisma** [comment]
That's good to hear. So it sounds like the problem was mainly with your environment. I'll close this.

**Comment by Delicious-Bacon** [comment]
@tonimelisma can you check it if it's reproducible?

If it is, it might be something with the vips' `brew install vips` command—if it sees that brew already has `brew install gcc`, it doesn't install it and maybe skips registering the path to it.

I am just taking hard guesses here, but that's how I had the issue.

**Comment by tonimelisma** [comment]
Hey @Delicious-Bacon unfortunately I can't. I'm a maintainer for govips, which is a Golang library utilizing libvips. Sounds like your problem is with the homebrew installation of libvips. Perhaps you can find out who the maintainer of that is and file a bug report in their repo?
