### ISSUE TITLE
Why are some functions unsupported?

### ISSUE THREAD

**Issue by medakk** [davidbyttow/govips#29]
I need to use bandjoin and pngsave_buffer in my application, but these functions are marked as "unsupported" [in this file](https://github.com/davidbyttow/govips/blob/10c2ddc9671420de77cb381dc01452c0f49752ab/operators.go#L20). 

Why are these functions unsupported? Is there any way I could workaround it and enable them while compiling the bindings?

**Comment by davidbyttow** [comment]
They could be supported, just needs some more work to the gen-operators file, it wasn't something totally required at first, but I could probably get it going

**Comment by tonimelisma** [comment]
Hey @medakk! We've now integrated a bunch of new functionality. BandJoin() and importing and exporting PNG images is now supported! Apologies for the delays.
