### ISSUE TITLE
Convert ndpi to dzi

### ISSUE THREAD

**Issue by SergeantSergey** [davidbyttow/govips#296]
I am a beginner Go developer. Can you please tell me if the library can convert ndpi to dzi ? Preferably with an example.
My code now looks like this, but it doesn't work:
```
        vips.Startup(nil)
	defer vips.Shutdown()

	image1, err := vips.NewImageFromFile("1.ndpi")
	checkError(err)

	params := vips.NewJpegExportParams()
	image1bytes, _, err := image1.ExportJpeg(params)
	err = ioutil.WriteFile("output.png", image1bytes, 0644)
	checkError(err)

```

The error I am getting is
```
2022/07/28 11:41:43 [VIPS.warning] Unknown field with tag 65476 (0xffc4) encount
ered
2022/07/28 11:41:43 [VIPS.info] vips__open_image_write: opening with O_TMPFILE
2022/07/28 11:41:43 [VIPS.info] vips__open_image_write: O_TMPFILE failed!
2022/07/28 11:41:43 [VIPS.info] vips__open_image_write: simple open
```

**Comment by tonimelisma** [comment]
Hey @SergeantSergey. The Github issues functionality is meant to file bug reports if you've found clear problems with govips. I recommend finding a Golang Slack server or forum where you could present your question and learn more. Apologies, but the govips maintainers don't have capacity.
