### ISSUE TITLE
Histogram calculations?

### ISSUE THREAD

**Issue by oschrenk** [davidbyttow/govips#303]
I'm trying to find fast ways to get the histogram as text/json of rather large 16bit tiff files. I was hoping that govips can help.

Does the library have bindings for histogram calculations? I managed only to find the `VIPS_INTERPRETATION_HISTOGRAM` but not the functions shown at https://www.libvips.org/API/current/libvips-histogram.html

Is histogram calculation supported?

**Comment by dommmel** [comment]
I added `vips_hist_find` here: https://github.com/davidbyttow/govips/pull/340 but cannot really take it further.

**Comment by rafaelsierra** [comment]
I am not sure why #340 was closed, but I opened #395 to add the same function back plus a few other supporting functions that I need

**Comment by tonimelisma** [comment]
Closing as resolved.
