### ISSUE TITLE
Unable to install latest version

### ISSUE THREAD

**Issue by medakk** [davidbyttow/govips#31]
Hello,

I'm try to install govips using `go get -u github.com/davidbyttow/govips`, but I'm getting this error message:
```
package github.com/davidbyttow/govips: no Go files in /home/karthik/Documents/programs/go/src/github.com/davidbyttow/govips
```

I'm only able to install it after checking out to a different commit (3c5a4d89f2ea8ce605bbdad8cf3aa3737a7228a6).
(due to [another issue](https://github.com/gographics/imagick/issues/155#issuecomment-365823479), I had to run `export CGO_CFLAGS_ALLOW='-fopenmp'` before installing)

Go version:
```
~$ go version
go version go1.9.4 linux/amd64
~$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/karthik/Documents/programs/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build385530049=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
```

**Comment by oikyn** [comment]
Maybe correctly, 
```
go get -u github.com/davidbyttow/govips/pkg/vips
```

Since `1.0.0` version, usable go files are in the `pkg/vips` directory.

**Comment by ex-nerd** [comment]
I needed this, with homebrew for other packages:
```bash
CGO_CFLAGS_ALLOW="-Xpreprocessor" \
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/local/opt/libffi/lib/pkgconfig" go get -u \
    github.com/davidbyttow/govips/pkg/vips
```

**Comment by tonimelisma** [comment]
Hey @medakk, @ex-nerd and @oikyn apologies for the delays but the README and documentation have now been updated in addition to fixing the build system. These bugs should bother anymore. Please reopen or comment if there's any problems!
