### ISSUE TITLE
VipsJpeg: Corrupt JPEG data

### ISSUE THREAD

**Issue by jishi92** [davidbyttow/govips#319]
I have a bad case when I use ThumbnailWithSize to resize my image and then ExportJpeg to []byte.Govips return error but the cmd just return a wraning msg and a effective thumbnail image.

`vips thumbnail bad-jpeg.jpg bad-jpeg-smaller.jpeg 100 --height=200 --size=force`

`"VipsJpeg: Corrupt JPEG data: 55319 extraneous bytes before marker 0xda\n\nStack:\ngoroutine 288 [running, locked to thread]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x65\ngovips/vips.handleVipsError()\n\t/govips/vips/error.go:38`

what should I do to fix it?

**Comment by jishi92** [comment]
fix it by fail_on level

**Comment by mholt** [comment]
@jishi92 Are you referring to FailOnError? https://pkg.go.dev/github.com/davidbyttow/govips/v2@v2.14.0/vips#ImportParams.FailOnError

What did your code look like?

**Comment by mholt** [comment]
Nevermind, should have trialed-and-error'ed:

```go
importParams := vips.NewImportParams()
importParams.FailOnError.Set(false)
```
