### ISSUE TITLE
Image Resizing Failing For GIFs Frame Too Large

### ISSUE THREAD

**Issue by Hrishikesh-Thakkar** [davidbyttow/govips#335]
I am trying to resize the following [GIF](https://gasfn25jo7ihtd6hweq44q3lymldirlacwdy5cjadirnjuhpomiq.arweave.net/MCRW66l30HmPx7EhzkNrwxY0RWAVh46JIBoi1NDvcxE) 

Original Dimensions are: 1270 x 1270 and a total of 149 Pages

I am resizing to the following Dimensions:
1. 250 x 250 (**Successful**)
2. 500 x 500 (**Successful**)
3. 750 x750 (**Unsuccessful**)

It fails for the last case and after some digging I found that the limits are set in [libvips](https://github.com/libvips/libvips/blob/v8.13.0/libvips/foreign/cgifsave.c#L715-L726). I am not able to conclude how the dimensions are violating the constraints. 

Constraints Being: 
`
	/* Reject images that exceed the pixel limit of libimagequant,
	 * or that exceed the GIF limit of 64k per axis.
	 *
	 * Frame width * height will fit in an int, though frame size will
	 * need at least a uint.
	 */
	if( (guint64) frame_rect.width * frame_rect.height > INT_MAX / 4 || 
		frame_rect.width > 65535 || 
		frame_rect.height > 65535 ) {
		vips_error( class->nickname, "%s", _( "frame too large" ) );
		return( -1 );
	}`

Currently I have the latest govips(v2.11.0) and vips(8.13.3) versions installed.

**Comment by jcupitt** [comment]
Cross-posted on libvips and stackoverflow. I would close this issue unanswered, David.
