### ISSUE TITLE
ExportJpeg memory usage

### ISSUE THREAD

**Issue by fcuenca4** [davidbyttow/govips#341]
Hi! First of all, thanks for the great work you are putting into go-vips.

I have a long running k8s service that is currently converting images from different formats to jpeg on a synchronous way. 
The service is currently being hosted in EKS t2.large node with 6GB or ram and 1vCPU and, after doing some load testing, it can't process more than a hundred 300kb conversions without exhausting all the memory and getting OOM.

I've set `ENV MALLOC_ARENA_MAX=2`  and also tried multiple values but the difference in terms of successes is not big.

I'm using go-vips v2.11.0 and vips 8.12.2 with concurrency=2 cache_max_files=0 cache_max_mem=52428800 cache_max=100.

What's could be the reason for this behaviour? Is there any ideas that might help me debug the issue? I'm running out of ideas :)

Thanks
Fran

**Comment by axkirillov** [comment]
Did you resolve this issue?
