### ISSUE TITLE
Refactoring Old and deprecated code

### ISSUE THREAD

**Issue by Soul-Asylum** [davidbyttow/govips#349]
Guys, I have a project that contains a very old code, referring to govips v1, and I need to refactor it, but I'm having a lot of difficulty, would anyone know how to help me?

`func ResizeImage(imageBuffer *bytes.Buffer, width, height int) (*bytes.Buffer, error) {
	imageRef, _ := vips.LoadImage(imageBuffer)

	//msg := fmt.Sprintf("Initial image has width of %v and height of %v", imageRef.Width(), imageRef.Height())
	//fmt.Println(msg)

	imageBytes, _, err := vips.NewTransform().
		Image(imageRef).
		Interpretation(vips.InterpretationSRGB).
		PadStrategy(vips.ExtendWhite).
		Resize(width, height).
		Apply()

	if err != nil {
		return nil, err
	}

	return bytes.NewBuffer(imageBytes), nil
}`

**Comment by tonimelisma** [comment]
Hey, thanks for the question. The API has been pretty completely revamped and doesn't support method chaining anymore. I recommend you just check the current documentation.
