### ISSUE TITLE
Migrate image operations from ImageMgaick to govips

### ISSUE THREAD

**Issue by WeisiminPeng-Simmi** [davidbyttow/govips#371]
Hi govips team, I am considering migrate some image operations from `ImageMagick` to `govip`, could you please help me confirm if below operations support in `govips` or not? Thanks!

1. resize
2. crop
3. padding
4. create an image and draw a circle on it (also fill the circle).
5. add drop shadow
6. gaussian blur

**Comment by tonimelisma** [comment]
Hey @WeisiminPeng-Simmi, you can find the govips documentation on godoc. Many libvips functionality is not supported as we haven't created wrapper functions for everything yet, but we're happy to merge PRs.
