### ISSUE TITLE
sharp resize vs govips resize

### ISSUE THREAD

**Issue by mfahmirukman** [davidbyttow/govips#372]
Hi, I want to ask if govips provide this resizing feature like the one in [sharp](https://github.com/lovell/sharp)

Reference to API: [API Resize](https://sharp.pixelplumbing.com/api-resize)

![image](https://github.com/davidbyttow/govips/assets/20079170/94154f3f-62fe-4e8a-8c2e-1b114d22a8f1)

**Comment by g-mero** [comment]
You can check 'ThumbnailWithSize' and 'Thumbnail' method, there is a crop argument seems like what you want to fullfill.

**Comment by mfahmirukman** [comment]
Thank you. I will try this
