### ISSUE TITLE
ubuntu20: libvips-dev provided by ppa:tonimelisma/ppa is not available anymore

### ISSUE THREAD

**Issue by mrngm** [davidbyttow/govips#378]
Since a couple of months (we noticed it early April 2023), the PPA mentioned in [the README](https://github.com/davidbyttow/govips/blob/c6838fceef8d93bca9e044187a412540b62c6090/README.md?plain=1#L36) is not accessible anymore.

I'm not sure if there are plans to revive the PPA (provided by @tonimelisma at the time), but it might be a good idea to let the README reflect the current state of this dependency.

**Comment by tonimelisma** [comment]
Hey @mrngm thanks for the feedback, you're completely correct. I retired the PPA as I didn't see many people using it as new Ubuntu versions were out. Do you still have a need for the old backported libvips packages for Ubuntu?

If so, the Dockerfiles needed for easy building your own dpkgs are here:

https://github.com/tonimelisma/libvips-dev-tonimelisma

I'll remove it from the README

**Comment by mrngm** [comment]
Hi @tonimelisma we're currently at Ubuntu 20.04, and we irregularly introduce new VMs that need `libvips` as well for these `govips` bindings. This LTS is (as far as Ubuntu is concerned) supported until April 2025. I suppose it wouldn't hurt to keep the PPA online during the expected support timeline of the LTS, if it's not _too_ much of a hassle.

From your comment I see that you intend to keep the PPA offline. In that case, we can build the package ourselves using the Dockerfiles you provided.

Thanks for clarifying the README!

**Comment by tonimelisma** [comment]
Thanks @mrngm - I'm really sorry as I didn't realize people were still using it. Unfortunately there's no easy way to restore the PPA. You'll probably set one up as easy as I would set mine up again so yeah, go ahead and use the Dockerfiles to build the packages. You can also, while you're at it, build newer versions if you will.
