### ISSUE TITLE
JPEG-XL support

### ISSUE THREAD

**Issue by devhaozi** [davidbyttow/govips#379]
Hi, libvips currently supports JPEG-XL (via libjxl), is there any plan for govips to add it?

link: libvips/libvips#2181

**Comment by songjiayang** [comment]
Hi @devhaozi  I have a fork to support jxl, pr check please https://github.com/imagecodex/govips/pull/7

**Comment by devhaozi** [comment]
> Hi @devhaozi I have a fork to support jxl, pr check please [imagecodex#7](https://github.com/imagecodex/govips/pull/7)

Good job, guy! Can you send a PR to this repository?

**Comment by DundieWinner** [comment]
@songjiayang Great work! can you please submit a PR to the origin project?

**Comment by songjiayang** [comment]
PR added, code review pls. @DundieWinner
