### ISSUE TITLE
libvips header

### ISSUE THREAD

**Issue by gertcuykens** [davidbyttow/govips#41]
http://jcupitt.github.io/libvips/API/current/libvips-header.html

If am not mistaken the above libvips header seems to be missing in govips

**Comment by tonimelisma** [comment]
Hey @gertcuykens apologies for the long delay. We've done a major upgrade to v2 with govips and most of the useful functions should be included in govips, such as getting height/width, orientation, etc. Is there anything else in particular you need? Can you describe the use case?

**Comment by gertcuykens** [comment]
It's ok this ticket can be closed, feel free to reopen if somebody has issues.
