### ISSUE TITLE
'for' loop initial declarations are only allowed in C99 mode

### ISSUE THREAD

**Issue by dAvagimyan** [davidbyttow/govips#426]
Hi there! I have an old OS (centos 7) in production and there is no way to update it or change the C++ assembly libraries.
I got next error in building my app. I can't use the option
-std=c99 since this should be used in the library itself. You have to copy the package and change the code manually. Is it possible to make the code backwards compatible for the old builder?
`int i;
for (i = 0; i < n_pages; i++) {
`
 or may be you can add
 `// #cgo CFLAGS: -std=c99` in conversion.go?
```
conversion.c: In function 'extract_area_multi_page':
conversion.c:147:3: error: 'for' loop initial declarations are only allowed in C99 mode
   for (int i = 0; i < n_pages; i++) {
```

**Comment by tonimelisma** [comment]
Ehhh. I suppose if you produce a PR and show that it doesn't break any tests on newer OS I could approve it.

**Comment by dAvagimyan** [comment]
https://github.com/davidbyttow/govips/pull/427/files
