### ISSUE TITLE
SVG embedded PNG/JPG dimensions limit

### ISSUE THREAD

**Issue by Melomate** [davidbyttow/govips#437]
When trying to convert a SVG which contains png/jpg images (for example resolution 15,000 X 15,000 px)
conversion result is just a blank image.

10,000 X 10,000px is working without issues

Can't tell whats the exact limit. Is it possible to remove that limit?

**Comment by tonimelisma** [comment]
Hey @Melomate. Thanks for the query. Unfortunately I don't have the information at hand. I'm not sure if it's something we would have implemented in govips or whether this is something upstream or perhaps a bug in govips resulting from the interactions.

Is it possible you look at debugging the issue yourself?
