### ISSUE TITLE
Diagonally watermark

### ISSUE THREAD

**Issue by Dumra** [davidbyttow/govips#438]
Hey, @tonimelisma .
Is the a way rotate watermark (Label) diagonally and spread it on the whole document w/o call Label function few times with other coordinates? 

Found that tricky way in python binding for libvips https://github.com/libvips/pyvips/blob/master/examples/watermark.py

But not sure that it could be repeat via govips.

Thanks.

**Comment by tonimelisma** [comment]
Hey, apologies but I'm oveeseas for the next few weeks. I'm terirbly sorry but we don't have bandwidth to help with how-tos. I recommend you read the docs and the source code. Sorry I can't be of more help.
