### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mickael-kerjean** [davidbyttow/govips#44]
Hello there,

I'm trying to use this lib as it's recommended by the author of libvips, made up some test in a docker container in order to monitor resource usage and found out memory isn't free after use. I'm not sure what can be done from my end. Reproduction code

``` golang

func CreateThumbnail(t *Transform, file io.Reader) (io.Reader, error) {
	v := vips.NewTransform().Load(file).ResizeWidth(t.Size)
	_, _, err := v.Apply()
	return file, nil
}
```

From my tests, as soon as the call to apply is made, the leak is starting and memory is never free. The behavior is everytime the code run through govips, I see ram comsumption growing by 2MB and seem to remain stable around 100MB, this 100MB is never garbage collected.

What can I do? Am I using govips wrong? I noticed the README isn't up to date and couldn't find any documentation out of the go doc.

There's no memory leak when I shortcut govips:
```
func CreateThumbnail(t *Transform, file io.Reader) (io.Reader, error) {
	return file, nil
}
```
The full code is [here](https://github.com/mickael-kerjean/nuage/blob/golang/server/services/images/thumbnail.go)

PS: I'm trying to use govips for [this project](https://github.com/mickael-kerjean/nuage)

**Comment by mickael-kerjean** [comment]
Alrighty, after hours of struggle, it seems to be coming from [here](https://github.com/davidbyttow/govips/blob/b2ed538870a851bfda2d69007ce56beda763ef0a/pkg/vips/govips.go#L18-L20), what I thought was a memory leak appears to be some sort of cache that's never drop

**Comment by mickael-kerjean** [comment]
I'm closing this in favor of using CGO to avoid unecessary abstractions

**Comment by evanoberholster** [comment]
I am having the same problem. Does anyone know of a solution? thanks

**Comment by mickael-kerjean** [comment]
My solution was to ditch govips and use libvips [directly](https://github.com/mickael-kerjean/nuage/blob/master/server/plugin/image_light/lib/resizer.go), it works great.
