### ISSUE TITLE
Undefind referances when building a go binary that uses govips 

### ISSUE THREAD

**Issue by gozes** [davidbyttow/govips#446]
So I'm trying to build a service that uses govips for image processing.

I'm building on Amazon Linux 2023 with added Fedora 40 repos to get the dependency need to build  use vips, the c library not the go library, however while vips install fine I get the below error when trying to build the service  that uses govips

after doing some digging I discover that dose functions are comming from glib2. 

after adding dose dependency and trying to build to  again I still get the same error even with glib2 installed
below is the install command and the error. 

```sh
dnf install -y vips vips-devel vips-tools glib2 glib2-devel glib2-static gobject-introspection
```

```sh
#23 95.94 /usr/bin/ld: /usr/lib/gcc/x86_64-amazon-linux/11/../../../../lib64/libvips.so: undefined reference to `g_once_init_enter_pointer'
#23 95.94 /usr/bin/ld: /usr/lib/gcc/x86_64-amazon-linux/11/../../../../lib64/libvips.so: undefined reference to `g_string_free_and_steal'
#23 95.94 /usr/bin/ld: /usr/lib/gcc/x86_64-amazon-linux/11/../../../../lib64/libvips.so: undefined reference to `g_once_init_leave_pointer'
```

feel like I'm missing a pice of the puzzle here

**Comment by tonimelisma** [comment]
Hey @gozes. Thanks for raising the issue. It seems like you have a dependency management issue that's outside of the govips golang library. I'm terribly sorry but we don't have resources to help with topics outside of the library.

I and other people have found better luck with e.g. ubuntu images.
