### ISSUE TITLE
govips slow compress

### ISSUE THREAD

**Issue by Nghiait123456** [davidbyttow/govips#448]
i have 20 pods in product, one node 124 core cpu, 80 GB ram

this problem:
  every 20 request,  have 18 request run about 1 second, and 2 request run very slow with 10 second
  help me debug this problem, i use vips-8.14.1

**Comment by tonimelisma** [comment]
Hey @Nghiait123456. Thanks for the issue report but unfortunately this is an open source project with no paid maintainers. We don't have any capacity to help with debugging complex production issues that could stem from govips, libvips, your environment or a multitude of other issues.
