### ISSUE TITLE
g_object_unref: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by tczf1128** [davidbyttow/govips#45]
so many errors when I run , what's the reason?

**Comment by xmackex** [comment]
Got the same issue.
```
(govips:45221): GLib-GObject-CRITICAL **: 02:46:21.849: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Was able to reproduce with
```
	vips.Startup(&vips.Config{
		ConcurrencyLevel: 1,
		MaxCacheFiles:    100,
		MaxCacheMem:      104857600,
		MaxCacheSize:     1,
		ReportLeaks:      true,
		CacheTrace:       true,
		CollectStats:     true,
	})
```
libvips version: 8.6.4

**Comment by oleh-ozimok** [comment]
ping

**Comment by oleh-ozimok** [comment]
hotfix, comment this line https://github.com/davidbyttow/govips/blob/master/pkg/vips/transform.go#L373

**Comment by davidbyttow** [comment]
Thanks, will fix!

**Comment by davidbyttow** [comment]
Also, I don't think this is that easy, I think it's only when it needs to convert the colorspace. I will address.

**Comment by davidbyttow** [comment]
Fixed: https://github.com/davidbyttow/govips/commit/b66f7b4cc75b07ebe5c466b4492a54a7aefda62a

**Comment by oleh-ozimok** [comment]
concurrent run this code will generate g_object_unref assertion (not only when it needs to convert the colorspace)

`
image, _ := vips.NewImageFromBuffer(blob)	

transform := vips.NewTransform().
		Image(image).
		Format(vips.ImageTypeJPEG).
		Quality(100).
		StripMetadata().Apply()
`

**Comment by davidbyttow** [comment]
Oh, that use case.. yeah, I see. OK

**Comment by ljs-cxm** [comment]
I have got some more error. Did it have been fixed?
my libvips version is:
`[root@localhost ~]# vips --version
vips-8.6.5-Wed Jul 25 09:46:22 UTC 2018
memory: high-water mark 0 bytes`

error messages are:
`(govips:5276): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '(null)'

(govips:5276): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(govips:5276): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
vips_image_dispose: temp-413 vips_reducev_gen computed 107%

(govips:5276): GLib-GObject-WARNING **: instance of invalid non-instantiatable type '<invalid>'

(govips:5276): GLib-GObject-CRITICAL **: g_signal_handler_is_connected: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(govips:5276): GLib-GObject-CRITICAL **: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
end image.go transform func
`

**Comment by tonimelisma** [comment]
Thanks everyone for the bug reports @ljs-cxm @tczf1128 @oleh-ozimok @xmackex . We've progressed to v2.0.2 and these should now be fixed. I'll close this generic report for now, I know it's been quite some time but can you please try and replicate bugs, and open issues with code samples to showcase clearly how to reproduce any bugs you get?
