### ISSUE TITLE
vips magicksave original.jpg test.gif

### ISSUE THREAD

**Issue by gertcuykens** [davidbyttow/govips#46]
Hi, there is a new magicksave operation in vips version 8.7
https://github.com/jcupitt/libvips/issues/839

**Comment by tczf1128** [comment]
I want this too

**Comment by tonimelisma** [comment]
Cool beans. Thanks for the feature request @gertcuykens. Considering we just got to v2 of govips with plenty of support for different file formats, is there still a need for magicksave? What specific use case?

**Comment by gertcuykens** [comment]
No need, can be closed.
