### ISSUE TITLE
How to measure progress of image transformations?

### ISSUE THREAD

**Issue by derpycoder** [davidbyttow/govips#460]
Hey Team,

I use h2non/bimg, however I am running into a edge case, I need to actually measure the progress of image transformation.

How can that be done with govips?

Does the lib support the eval signals?

**Comment by tonimelisma** [comment]
Hey @derpycoder I don't believe we do. I would check with the underlying libvips if anything major has changed and they would have support for something like this. If so, it shouldn't be too hard to add the features to govips.

**Comment by derpycoder** [comment]
@tonimelisma ,

There’s eval signal: https://www.libvips.org/API/current/VipsImage.html#vips-image-set-progress

The ::eval signal is emitted once per work unit (typically a 128 x 128 area of pixels) during image computation.

You can use this signal to update user-interfaces with progress feedback. Beware of updating too frequently: you will usually need some throttling mechanism.

Use [vips_image_set_progress()](https://www.libvips.org/API/current/VipsImage.html#vips-image-set-progress) to turn on progress reporting for an image.

**Comment by tonimelisma** [comment]
That makes sense. If you were to submit a PR according to the contributions document (i.e. include documentation, tests etc) I'd be more than happy to review and merge!
