### ISSUE TITLE
label error

### ISSUE THREAD

**Issue by ljs-cxm** [davidbyttow/govips#49]
Hi, I want to complete watermarking with transform.Label, but I got a error. What's wront with it？
`package main

import (
	"fmt"
	"io/ioutil"

	"github.com/davidbyttow/govips/pkg/vips"
)

func main() {
	ref, _ := vips.NewImageFromFile("./aaa.PNG")
	lp := &vips.LabelParams{Text: "hello world"}

	buf, _, err := vips.NewTransform().
		Image(ref).
		Label(lp).
		Apply()
	fmt.Println("buf: %v", buf)
	fmt.Println("err: %v", err)

	ioutil.WriteFile("./xxx.png", buf, 664)
}
`

2018/09/20 02:02:48 libvips was forcibly started automatically, consider calling Startup/Shutdown yourself
2018/09/20 02:02:48 Vips started with concurrency=1 cache_max_files=100 cache_max_mem=104857600 cache_max=500
2018/09/20 02:02:48 Registered image type loader type=jpeg
2018/09/20 02:02:48 Registered image type loader type=magick
2018/09/20 02:02:48 Registered image type loader type=pdf
2018/09/20 02:02:48 Registered image type loader type=png
2018/09/20 02:02:48 Registered image type loader type=svg
2018/09/20 02:02:48 Registered image type loader type=tiff
2018/09/20 02:02:48 Registered image type loader type=webp
2018/09/20 02:02:48 Registered image type loader type=gif
buf: %v []
err: %v VipsOperation: class "text" not found

Stack:
goroutine 1 [running]:
runtime/debug.Stack(0x7faea9dffac0, 0xc00001c210, 0x26)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/davidbyttow/govips/pkg/vips.handleVipsError(0x0, 0x0)
	/root/go/src/github.com/davidbyttow/govips/pkg/vips/bridge.go:457 +0x9d
github.com/davidbyttow/govips/pkg/vips.vipsLabel(0x18cb190, 0x4e22d0, 0xb, 0x4e19d9, 0x7, 0x3ff0000000000000, 0x1, 0x3ff0000000000000, 0x1, 0x0, ...)
	/root/go/src/github.com/davidbyttow/govips/pkg/vips/bridge.go:446 +0x439
github.com/davidbyttow/govips/pkg/vips.postProcess(0xc00008a140, 0x0, 0x0)
	/root/go/src/github.com/davidbyttow/govips/pkg/vips/transform.go:692 +0x152
github.com/davidbyttow/govips/pkg/vips.(*Transform).transform(0xc000097ec8, 0x18cb190, 0x3, 0x0, 0x0, 0xc000097df0)
	/root/go/src/github.com/davidbyttow/govips/pkg/vips/transform.go:483 +0x77
github.com/davidbyttow/govips/pkg/vips.(*Transform).Apply(0xc000097ec8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/src/github.com/davidbyttow/govips/pkg/vips/transform.go:348 +0xe1
main.main()
	/root/go/src/test.go:19 +0x1ca

**Comment by tonimelisma** [comment]
Hey @ljs-cxm - thanks for the bug report and apologies for little action on this.

We've made major upgrades in terms of functionality as well as bug fixes. The API has changed and we're now in v2.0.0. 

In any case I will attempt to reproduce this bug once time is willing.

**Comment by tonimelisma** [comment]
Yup, this is replicated on v2.0.2, label() throws ```(govips:3910961): GLib-GObject-CRITICAL **: 23:42:48.640: g_object_unref: assertion 'G_IS_OBJECT (object)' failed````

Will investigate!

**Comment by tonimelisma** [comment]
Hey @ljs-cxm it works for me. Be sure to include all the relevant parameters in the labelParams struct.
