### ISSUE TITLE
Add support for Linear1

### ISSUE THREAD

**Issue by xzyfer** [davidbyttow/govips#50]
[vips_linear][] is the work horse of libvips. With it alone all manner of manipulations are possible. libvips exposes a simpler [vips_linear1][] interface that's more inline with the already exposed `Composite` operation.

I can see that linear1 support exists in the binding as it it used internally. However my attempts to expose it keep running into SIGSEVs locally. I may be missing something.

[vips_linear]: https://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-linear
[vips_linear1]: https://jcupitt.github.io/libvips/API/current/libvips-arithmetic.html#vips-linear1

**Comment by tonimelisma** [comment]
Hey @xzyfer apologies for the delay. We've recently merged a bunch of great functionality from a port and Linear1() support is in there! Please check it out and let me know if there's any issues.
