### ISSUE TITLE
Loading images through *magick

### ISSUE THREAD

**Issue by eriken** [davidbyttow/govips#51]
First off, thanks for making these bindings.

I am trying to make use of the vips *magick wrapping functionality.
I have gone through your code and see references to loading images with this feature. But I cannot figure out how to make use of it. 
`NewImageFromBuffer()` seem to be able to support it. But then `ImageTypeMagick` cannot be passed nor is it ever set programtically; https://github.com/davidbyttow/govips/blob/master/pkg/vips/bridge.go#L126

Is this intentionally disabled or could I help tweak the API so the caller can hint the `ImageType`.

Regards Erik

**Comment by davidbyttow** [comment]
We could tweak the API to support this!

**Comment by eriken** [comment]
Cool.

After trying out a lot of solutions for our services we ended up with a solution relying on the ImageMagick CLI for pure robustness.

I might have another go at vips with golang bindings at a later stage. Maybe I can contribute something then.

Regards Erik
