### ISSUE TITLE
support access type for image loader

### ISSUE THREAD

**Issue by toaster** [davidbyttow/govips#54]
Hi there,

I am in need of support for specifying the access type on image load. I would implement it on my own and open a pull request.

Should I use an approach compatible to #26 so it gets easier to join the two PRs?

Also, I found that there is already a type `Access` which seems to be unused ATM.
Where there already plans to support the access type on image loading?

Best Regards

Tilo

**Comment by davidbyttow** [comment]
Yes, I'm happy to take on a PR for this!

**Comment by toaster** [comment]
Here you go: #56 

Thanks in advance
