### ISSUE TITLE
Is the readme outdated?

### ISSUE THREAD

**Issue by devmarco** [davidbyttow/govips#59]
I'm trying to follow the example and using `NewPipeline`, but it seems that it does not exist, also I didn't found that method in the go docs https://godoc.org/github.com/davidbyttow/govips/pkg/vips#Transform.LoadBuffer

**Comment by adueck** [comment]
@devmarco. I had the same problem, I needed to this to get a transform working:

```
	// Resize Image
	_, _, err = vips.NewTransform().
		LoadFile(originalFile).
		ResizeStrategy(vips.ResizeStrategyAuto).
		ResizeWidth(800).
		OutputFile(convertedFile).
		Apply()
```

**Comment by mohit810** [comment]
on installation using  ```
go get -u github.com/davidbyttow/govips/pkg/vips
# 
```
I am getting

```
pkg-config --cflags  -- vips vips vips vips vips vips vips vips vips
pkg-config: exec: "pkg-config": executable file not found in %PATH%

```

**Comment by tonimelisma** [comment]
Considering the readme documentation hasn't been updated in two years to provide a working example, might be a good idea to migrate to this fork which is maintained: https://github.com/wix-playground/govips

**Comment by tonimelisma** [comment]
Hey @mohit810 @devmarco @adueck - apologies for the slumber. The README, documentation etc has been now updated and everything should work. The API has changed. Please check it out and comment or re-open if you have any issues!
