### ISSUE TITLE
panic if using icc_import with libvips w/o ICC support

### ISSUE THREAD

**Issue by toaster** [davidbyttow/govips#63]
When using `IccImport` with a libvips that was build without ICC support a panic occurs.
It would safe a lot of debugging time if ICC related functions were protected by using `vips_icc_present()`.

There are probably many other functions depending on other non-vips libs with the same problem.
However, a meaningful error would be nice.

**Comment by tonimelisma** [comment]
Thanks @toaster that's a great idea. Apologies for the delays in responding. Do you think this is something you might be interested in helping out with a PR?

**Comment by toaster** [comment]
Yes, but it might take some time for me to get to it :).

**Comment by tonimelisma** [comment]
Hey @toaster this is fixed. Thanks for the bug report.

**Comment by davidbyttow** [comment]
Nice!
