### ISSUE TITLE
Using `NewImageRef` leads to g_object_unref assertion failed errors.

### ISSUE THREAD

**Issue by sherifabdlnaby** [davidbyttow/govips#71]
Hello,

I am trying to do some operations on an image and then after that I'll generate multiple variants from the base image.

So I use `NewImageRef()` to generate a new ImageRef for each variant I want to have from the base ImageRef.

Now these ImageRef(s) or the base ImageRef are then returned from the calling function based on some logic.

But then I get tons of 
```shell
(govips:86726): GLib-GObject-CRITICAL **: 04:01:24.535: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(govips:86726): GLib-GObject-CRITICAL **: 04:01:24.537: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(govips:86726): GLib-GObject-CRITICAL **: 04:01:24.540: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

When I pass only return base ImageRef from all my functions, no errors happen, but of course that doesn't achieve what I want. so once I have another ImageRef created from the base ImageRef via `NewImageRef` and I return it instead of the base ImageRef the error occurs.

**Comment by tonimelisma** [comment]
Hey @sherifabdlnaby - we've had a major upgrade to v2. Can you check if you still have issues?

**Comment by bozaro** [comment]
For same reason I use `ImageRef.Copy()` method. But in v2 this method is deprecated.
Why was it deprecated and what is the proposed alternative?

**Comment by tonimelisma** [comment]
Hey @bozaro you can just use Copy(), [documentation here](https://pkg.go.dev/github.com/davidbyttow/govips/v2@v2.0.2/vips#ImageRef.Copy)

Basically just
```imageCopy, err := imageRef.Copy()```

It's not deprecated, I'll update the documentation.
