### ISSUE TITLE
Some Image Types Not Supported

### ISSUE THREAD

**Issue by freedombird9** [davidbyttow/govips#76]
Currently it does not support OpenSlide image formats (vms, kfb, vmu etc.).  The vips command line tool supports those formats by default.

The `DetermineImageType` function doesn't recognize them. I tried to add the support in Go code, but later found out the native function `C.vips_type_find()` always returns 0 on those formats.  Bypassing the image type check would later result in error at `C.init_image()`.

I wonder if any extra config is needed to support those formats?  Basically I need the `dzsave()` from `VipsForeignSave` module.

**Comment by freedombird9** [comment]
After a closer look, it seems this binding only supports buffer reads, where it reads the whole image into a buffer and builds a VipsImage object. But the OpenSlide images are usually very large, so `vips_openslideload()` just opens the file with header fields filled in. It then uses random access to process it later, for e.g, `dzsave()`.  This method doesn't have a buffer version. `vips_image_new_from_file()` uses a similar way.

I think to support all native vips operations, the binding needs to support read from file (no buffer) with random access first.

I'll see if I can implement some new APIs to handle that.

**Comment by tonimelisma** [comment]
Thanks - that would be greatly appreciated. Please see the comments on the PR.
