### ISSUE TITLE
Prefix releases with 'v'

### ISSUE THREAD

**Issue by mihaitodor** [davidbyttow/govips#82]
If possible, it might be a good idea to prefix future releases with a `v`. Otherwise, `go mod` will record a "pseudo-version" (something like "github.com/davidbyttow/govips v0.0.0-20190304175058-d272f04c0fea") in the `go.mod` file, which might trip up some users. Details [here](https://github.com/golang/go/issues/30146).

**Comment by tonimelisma** [comment]
Thanks @mihaitodor! We'll take this into consideration in the future!
