### ISSUE TITLE
HEIC support ?

### ISSUE THREAD

**Issue by bciceron** [davidbyttow/govips#83]
Hello,

i see libvips now supports HEIC:
- https://libvips.github.io/libvips/2019/04/22/What's-new-in-8.8.html
- https://github.com/strukturag/libheif/issues/129

Is there a build of govips with HEIC support in the works ?

cheers

**Comment by ItalyPaleAle** [comment]
FYI, I just found out this fork which seems to be better maintained (by Wix.com), and it does support libvips 8.8+ for HEIF: https://github.com/wix-playground/govips

**Comment by tonimelisma** [comment]
Hey @bciceron and @ItalyPaleAle - indeed, apologies for govips having been in a bit of a slumber. All the changes from the wix-playground fork are now integrated in govips including HEIC support, alongside some additional improvements and better documentation. Please comment or re-open if you have any issues getting it working! Thanks!
