### ISSUE TITLE
Custom backgroun extend doesn't work

### ISSUE THREAD

**Issue by HEKET313** [davidbyttow/govips#91]
I want to use a custom background with transformation. But when I use `Embed(vips.ExtendBackground)` - background is still black even if I set `transform.BackgroundColor(vips.Color{R:255,G:255,B:255})` for option `Embed(vips.ExtendWhite)` everything works fine.

**Comment by tonimelisma** [comment]
Hey @HEKET313 - I realise it's been quite some time without a reply. We've made major functionality upgrades and bugfixes, the API has also changed. This has likely been fixed. Can you try the latest and let me know if there's any more issues?

**Comment by tonimelisma** [comment]
Hey, I haven't seen any action in two weeks here so I'm closing. Please don't hesitate to reopen if you're still having issues and you need help.
