### ISSUE TITLE
VipsOperation: class "jpegload_buffer" not found

### ISSUE THREAD

**Issue by dcnug** [davidbyttow/govips#93]
go run cmd/examples/resize/resize.go -in assets/fixtures/canyon.jpg -out cmd/examples/build/resize-canyon.jpg
2019/12/27 23:52:26 Vips started with concurrency=1 cache_max_files=100 cache_max_mem=104857600 cache_max=500
2019/12/27 23:52:26 Registered image type loader type=gif
2019/12/27 23:52:26 Registered image type loader type=jpeg
2019/12/27 23:52:26 Registered image type loader type=magick
2019/12/27 23:52:26 Registered image type loader type=pdf
2019/12/27 23:52:26 Registered image type loader type=png
2019/12/27 23:52:26 Registered image type loader type=svg
2019/12/27 23:52:26 Registered image type loader type=tiff
2019/12/27 23:52:26 Registered image type loader type=webp
2019/12/27 23:52:26 VipsOperation: class "jpegload_buffer" not found

Stack:
goroutine 1 [running]:
runtime/debug.Stack(0x7f5c2ba02680, 0xc0000ac040, 0x31)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/davidbyttow/govips/pkg/vips.handleVipsError(0x0, 0x0)
	/home/tlab-n023/go/src/github.com/davidbyttow/govips/pkg/vips/bridge.go:474 +0x9e
github.com/davidbyttow/govips/pkg/vips.vipsLoadFromBuffer(0xc000146000, 0x703b3, 0x7fe00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tlab-n023/go/src/github.com/davidbyttow/govips/pkg/vips/bridge.go:150 +0x1ae
github.com/davidbyttow/govips/pkg/vips.(*Transform).importImage(0xc0000b7ef8, 0x4f9928, 0xc0000b7ef8, 0x0, 0x4f9d58)
	/home/tlab-n023/go/src/github.com/davidbyttow/govips/pkg/vips/transform.go:384 +0xe2
github.com/davidbyttow/govips/pkg/vips.(*Transform).Apply(0xc0000b7ef8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tlab-n023/go/src/github.com/davidbyttow/govips/pkg/vips/transform.go:352 +0xa3
main.resize(0x7ffecae5b1c0, 0x1a, 0x7ffecae5b1e0, 0x24, 0x0, 0x0)
	/home/tlab-n023/go/src/govips/cmd/examples/resize/resize.go:38 +0x1dd
main.main()
	/home/tlab-n023/go/src/govips/cmd/examples/resize/resize.go:25 +0xd4

**Comment by aureleoules** [comment]
Try building libvips from a GitHub [release](https://github.com/libvips/libvips/releases).

**Comment by tonimelisma** [comment]
Hey @dcnug and @aureleoules we've made major upgrade to govips. The API has changed and the requirement is now libvips 8.10. README has instructions on how to easily install dependencies. Apologies for the long delay. Hope the new version works well for you - please comment or reopen if there's any issues!
