### ISSUE TITLE
Optimizing PNG images

### ISSUE THREAD

**Issue by richp10** [davidbyttow/govips#96]
I have govips very succesfully aggresively optimizing images like this: 

```	
c, _, err := vips.NewTransform().
		LoadBuffer(b).
		Quality(15).
		StripMetadata().
		OutputBytes().
		Apply()
```

This reduces file size (at some cost to quality of course) for gif, jpg and svg images - but it is not having any impact on my sample PNG files (same with a tiff but I have not experimented much beyond one sample tiff). 

Any thoughts on using govips for lossy PNG optimization / compression?

**Comment by cchantep** [comment]
Same

**Comment by richp10** [comment]
@cchantep - I *think* the problem was that vips was not compiled with all the required png libraries including I think pngquant.  I have not quite tested this theory out properly - but suggest you look in that direction.

**Comment by cchantep** [comment]
Trying https://github.com/ultimate-guitar/go-imagequant

**Comment by tonimelisma** [comment]
Hey @cchantep and @richp10 apologies for not responding earlier. We've made a major upgrade of govips and the API has changed completely. Can you try with the latest version and indicate if you still have issues?

**Comment by tonimelisma** [comment]
Considering the PNG file format, the amount of compression itself just doesn't affect file size much, unfortunately. In addition it looks to me like libvips doesn't have capabilities to do any other tricks to bring down the size of PNGs: https://github.com/libvips/libvips/issues/1322

Likely you can't do better with libvips. Unfortunately it's not in the scope of govips to extend functionality to other libraries, but perhaps by checking that issue you can see if there's opportunities to expand libvips.

Apologies I can't be of more help here.
