### ISSUE TITLE
How do you read the average of individual bands after calling Bandmean method?

### ISSUE THREAD

**Issue by rapidcoder7** [davidbyttow/govips#97]
I have the below sample code in goLang where I am trying to read the average values of the individual bands. The average values are computed by calling the Bandmean() method. 

`err := vipsImageRef.Bandmean()
if err != nil {
    // throw some error
}

// try to print the average values of the bands but how? 
`

**Comment by tonimelisma** [comment]
Hey @rapidcoder7 apologies for the delays. bandmean() doesn't calculate average values for individual bands, it actually creates a new image where each pixel is an average of the bands of that pixel in the input image. Can you describe what you're trying to accomplish, not sure if libvips can help here?

**Comment by tonimelisma** [comment]
Closing for now. Happy to help if this is still relevant at some stage.
